import { Words } from "../drizzle/schema";
import { db } from "../drizzle/db";

async function seed() {

    console.log("Seeding database...");

    const userId = "user_2rLdvxl8OaqqsqX1Jv72KhuGq32"; 

    await db.insert(Words).values([
    // Colors
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "es tut mir leid", HebrewWord: "סליחה", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "entschuldigung", HebrewWord: "סליחה", knowlage: "?" , clerkUserId: userId },

    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "rot", HebrewWord: "אדום", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "blau", HebrewWord: "כחול", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "grün", HebrewWord: "ירוק", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "gelb", HebrewWord: "צהוב", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "schwarz", HebrewWord: "שחור" , knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "weiß", HebrewWord: "לבן", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "grau", HebrewWord: "אפור", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "braun", HebrewWord: "חום" , knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "rosa", HebrewWord: "ורוד", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "orange", HebrewWord: "כתום", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "lila", HebrewWord: "סגול", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "hellblau", HebrewWord: "תכלת", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "dunkelgrün", HebrewWord: "ירוק כהה", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "beige", HebrewWord: "בז'", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "violett", HebrewWord: "ארגמן", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "gold", HebrewWord: "זהב", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "silber", HebrewWord: "כסף", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "zinnober", HebrewWord: "אדמדם", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "kupfer", HebrewWord: "נחושת", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "karmin", HebrewWord: "קרמין", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "oliv", HebrewWord: "זית", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "türkis", HebrewWord: "טורקיז", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "indigo", HebrewWord: "אינדיגו", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "karmesinrot", HebrewWord: "אדום קרמזין", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "smaragdgrün", HebrewWord: "ירוק אזמרגד", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "bernstein", HebrewWord: "ענבר", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "mahagoni", HebrewWord: "מהגוני", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "schneeweiß", HebrewWord: "לבן שלג", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "kohlrabenschwarz", HebrewWord: "שחור כזפת", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 1, courseNameEnglish: "Colors", GermanWord: "kakao", HebrewWord: "קקאו", knowlage: "X" , clerkUserId: userId },

    // Numbers
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "eins", HebrewWord: "אחד", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "zwei", HebrewWord: "שתיים", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "drei", HebrewWord: "שלוש", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "vier", HebrewWord: "ארבע", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "fünf", HebrewWord: "חמש", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "sechs", HebrewWord: "שש", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "sieben", HebrewWord: "שבע", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "acht", HebrewWord: "שמונה", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "neun", HebrewWord: "תשע", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "zehn", HebrewWord: "עשר", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "elf", HebrewWord: "אחד עשרה", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "zwölf", HebrewWord: "שתים עשרה", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "dreizehn", HebrewWord: "שלוש עשרה", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "vierzehn", HebrewWord: "ארבע עשרה", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "fünfzehn", HebrewWord: "חמש עשרה", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "sechzehn", HebrewWord: "שש עשרה", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "siebzehn", HebrewWord: "שבע עשרה", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "achtzehn", HebrewWord: "שמונה עשרה", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "neunzehn", HebrewWord: "תשע עשרה", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "zwanzig", HebrewWord: "עשרים", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "einundzwanzig", HebrewWord: "עשרים ואחד", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "zweiundzwanzig", HebrewWord: "עשרים ושתיים", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "dreiundzwanzig", HebrewWord: "עשרים ושלוש", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "vierundzwanzig", HebrewWord: "עשרים וארבע", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "fünfundzwanzig", HebrewWord: "עשרים וחמש", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "sechsundzwanzig", HebrewWord: "עשרים ושש", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "siebenundzwanzig", HebrewWord: "עשרים ושבע", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "achtundzwanzig", HebrewWord: "עשרים ושמונה", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "neunundzwanzig", HebrewWord: "עשרים ותשע", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 2, courseNameEnglish: "Numbers", GermanWord: "dreißig", HebrewWord: "שלושים", knowlage: "?" , clerkUserId: userId },

    // Fammily Members
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Vater", HebrewWord: "אבא", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Mutter", HebrewWord: "אמא", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Bruder", HebrewWord: "אח", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Schwester", HebrewWord: "אחות", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Opa", HebrewWord: "סבא", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Oma", HebrewWord: "סבתא", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Onkel", HebrewWord: "דוד", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Tante", HebrewWord: "דודה", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Cousin", HebrewWord: "בן דוד", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Cousine", HebrewWord: "בת דוד", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Neffe", HebrewWord: "אחיין", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Nichte", HebrewWord: "אחיינית", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Enkel", HebrewWord: "נכד", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Enkelin", HebrewWord: "נכדה", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Schwager", HebrewWord: "גיס", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Schwägerin", HebrewWord: "גיסה", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Schwiegervater", HebrewWord: "חותן", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Schwiegermutter", HebrewWord: "חמות", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Schwiegersohn", HebrewWord: "חתן", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Schwiegertochter", HebrewWord: "כלה", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Ehemann", HebrewWord: "בעל", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Ehefrau", HebrewWord: "אשה", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Sohn", HebrewWord: "בן", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Tochter", HebrewWord: "בת", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Großvater", HebrewWord: "סבא רבא", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Großmutter", HebrewWord: "סבתא רבתא", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Urenkel", HebrewWord: "נין", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Urenkelin", HebrewWord: "נינה", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Halbbruder", HebrewWord: "אח למחצה", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 3, courseNameEnglish: "Family members", GermanWord: "Halbschwester", HebrewWord: "אחות למחצה", knowlage: "V" , clerkUserId: userId },

    // Days of the Week
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Montag", HebrewWord: "יום שני", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Dienstag", HebrewWord: "יום שלישי", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Mittwoch", HebrewWord: "יום רביעי", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Donnerstag", HebrewWord: "יום חמישי", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Freitag", HebrewWord: "יום שישי", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Samstag", HebrewWord: "שבת", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Sonntag", HebrewWord: "יום ראשון", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Wochenbeginn", HebrewWord: "תחילת שבוע", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Wochenende", HebrewWord: "סוף שבוע", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Montagmorgen", HebrewWord: "בוקר יום שני", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Dienstagabend", HebrewWord: "ערב יום שלישי", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Mittwochnachmittag", HebrewWord: "אחר הצהריים של יום רביעי", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Donnerstagnacht", HebrewWord: "לילה של יום חמישי", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Freitagmorgen", HebrewWord: "בוקר יום שישי", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Samstagabend", HebrewWord: "ערב שבת", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Sonntagvormittag", HebrewWord: "לפני הצהריים של יום ראשון", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Erster Tag", HebrewWord: "יום ראשון", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Letzter Tag", HebrewWord: "יום אחרון", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Arbeitstag", HebrewWord: "יום עבודה", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Ruhetag", HebrewWord: "יום מנוחה", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Gestern", HebrewWord: "אתמול", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Heute", HebrewWord: "היום", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Morgen", HebrewWord: "מחר", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Früher", HebrewWord: "לפני כן", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Später", HebrewWord: "אחרי כן", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Nächste Woche", HebrewWord: "שבוע הבא", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Letzte Woche", HebrewWord: "שבוע שעבר", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Zukunftstag", HebrewWord: "יום בעתיד", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Vergangener Tag", HebrewWord: "יום שעבר", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 4, courseNameEnglish: "Days of the Week", GermanWord: "Freie Tage", HebrewWord: "ימי חופשה", knowlage: "X" , clerkUserId: userId },

    // Months
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 5, courseNameEnglish: "Months", GermanWord: "Januar", HebrewWord: "ינואר", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 5, courseNameEnglish: "Months", GermanWord: "Februar", HebrewWord: "פברואר", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 5, courseNameEnglish: "Months", GermanWord: "März", HebrewWord: "מרץ", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 5, courseNameEnglish: "Months", GermanWord: "April", HebrewWord: "אפריל", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 5, courseNameEnglish: "Months", GermanWord: "Mai", HebrewWord: "מאי", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 5, courseNameEnglish: "Months", GermanWord: "Juni", HebrewWord: "יוני", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 5, courseNameEnglish: "Months", GermanWord: "Juli", HebrewWord: "יולי", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 5, courseNameEnglish: "Months", GermanWord: "August", HebrewWord: "אוגוסט", knowlage: "?" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 5, courseNameEnglish: "Months", GermanWord: "September", HebrewWord: "ספטמבר", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 5, courseNameEnglish: "Months", GermanWord: "Oktober", HebrewWord: "אוקטובר", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 5, courseNameEnglish: "Months", GermanWord: "November", HebrewWord: "נובמבר", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 5, courseNameEnglish: "Months", GermanWord: "Dezember", HebrewWord: "דצמבר", knowlage: "X" , clerkUserId: userId },

    // Greetings
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Wie heißen Sie", HebrewWord: "איך קוראים לך", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "ich", HebrewWord: "אני", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "heiße", HebrewWord: "קוראים", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Hallo", HebrewWord: "שלום", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Servus", HebrewWord: "שלום", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Guten Morgen", HebrewWord: "בוקר טוב", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Guten Tag", HebrewWord: "צהריים טובים", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Guten Abend", HebrewWord: "ערב טוב", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Gute Nacht", HebrewWord: "לילה טוב", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "hi", HebrewWord: "היי", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Wie geht's?", HebrewWord: "מה שלומך", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Auf Wiedersehen", HebrewWord: "להתראות", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Tschüss", HebrewWord: "ביי", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Bis bald", HebrewWord: "נתראה בקרוב", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Herzlich willkommen", HebrewWord: "ברוך הבא", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Schönen Tag noch", HebrewWord: "שיהיה לך יום נעים", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Viel Glück", HebrewWord: "בהצלחה", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Alles Gute", HebrewWord: "כל טוב", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Guten Appetit", HebrewWord: "בתיאבון", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Schlaf gut", HebrewWord: "שינה טובה", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Grüß Gott", HebrewWord: "ברך את ה'", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Moin", HebrewWord: "שלום (צפון גרמניה)", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Servus", HebrewWord: "שלום (דרום גרמניה)", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Prost", HebrewWord: "לחיים", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Schönen Abend noch", HebrewWord: "שיהיה לך ערב נעים", knowlage: "V" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Ich wünsche dir einen schönen Tag", HebrewWord: "אני מאחל לך יום נעים", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Bis später", HebrewWord: "נתראה מאוחר יותר", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Bis morgen", HebrewWord: "נתראה מחר", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Bis nächste Woche", HebrewWord: "נתראה בשבוע הבא", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Schön dich zu sehen", HebrewWord: "נחמד לראות אותך", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Es freut mich, dich zu treffen", HebrewWord: "שמחתי לפגוש אותך", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Ich freue mich, Sie zu sehen", HebrewWord: "שמחתי לראות אותך (רשמי)", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Ich hoffe, es geht dir gut", HebrewWord: "אני מקווה שאתה בסדר", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Herzlichen Glückwunsch", HebrewWord: "מזל טוב", knowlage: "X" , clerkUserId: userId },
    { levelHebrew: "מבוא", levelEnglish: "A1", courseId: 6, courseNameEnglish: "Greetings", GermanWord: "Frohes neues Jahr", HebrewWord: "שנה טובה", knowlage: "X" , clerkUserId: userId },

    // Weather
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es ist sonnig", HebrewWord: "יש שמש", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es ist wolkig", HebrewWord: "מעונן", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es regnet", HebrewWord: "יורד גשם", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es schneit", HebrewWord: "יורד שלג", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es ist windig", HebrewWord: "יש רוח", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es ist heiß", HebrewWord: "חם", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es ist kalt", HebrewWord: "קר", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es ist neblig", HebrewWord: "יש ערפל", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es ist stürmisch", HebrewWord: "סוער", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es ist trocken", HebrewWord: "יבש", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es ist nass", HebrewWord: "רטוב", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es gibt Gewitter", HebrewWord: "יש סופת רעמים", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es ist warm", HebrewWord: "חמים", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es ist kühl", HebrewWord: "קריר", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es ist wechselhaft", HebrewWord: "משתנה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es gibt einen Regenbogen", HebrewWord: "יש קשת בענן", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es hagelt", HebrewWord: "יורד ברד", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Der Himmel ist klar", HebrewWord: "השמיים בהירים", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Der Himmel ist bedeckt", HebrewWord: "השמיים מכוסים", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es gibt eine Hitzewelle", HebrewWord: "יש גל חום", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es gibt eine Kältewelle", HebrewWord: "יש גל קור", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es gibt starken Wind", HebrewWord: "יש רוח חזקה", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es gibt dichten Nebel", HebrewWord: "יש ערפל כבד", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es ist bewölkt", HebrewWord: "מעונן חלקית", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es ist schwül", HebrewWord: "לח מאוד", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es ist angenehm", HebrewWord: "נעים", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es gibt einen starken Sturm", HebrewWord: "יש סופה חזקה", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es gibt leichtes Nieseln", HebrewWord: "יש טפטוף קל", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es regnet in Strömen", HebrewWord: "יורד גשם כבד", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 7, courseNameEnglish: "Weather", GermanWord: "Es gibt einen Schneesturm", HebrewWord: "יש סופת שלגים", knowlage: "?" , clerkUserId: userId },

// Basic Clothing
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "das Hemd", HebrewWord: "חולצה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Hose", HebrewWord: "מכנסיים", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "das Kleid", HebrewWord: "שמלה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Jacke", HebrewWord: "מעיל", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Schuhe", HebrewWord: "נעליים", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Socken", HebrewWord: "גרביים", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Mütze", HebrewWord: "כובע צמר", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "der Hut", HebrewWord: "כובע", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Handschuhe", HebrewWord: "כפפות", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "der Schal", HebrewWord: "צעיף", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Bluse", HebrewWord: "חולצת נשים", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Unterwäsche", HebrewWord: "תחתונים", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "das T-Shirt", HebrewWord: "טי-שירט", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Jeans", HebrewWord: "ג'ינס", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Sandalen", HebrewWord: "סנדלים", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Stiefel", HebrewWord: "מגפיים", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Weste", HebrewWord: "אפוד", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "der Pullover", HebrewWord: "סוודר", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Krawatte", HebrewWord: "עניבה", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "das Kostüm", HebrewWord: "חליפה (נשים)", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "der Anzug", HebrewWord: "חליפה (גברים)", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Shorts", HebrewWord: "מכנסיים קצרים", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "der Mantel", HebrewWord: "מעיל ארוך", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Strümpfe", HebrewWord: "גרביים ארוכים", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "der Gürtel", HebrewWord: "חגורה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Regenjacke", HebrewWord: "מעיל גשם", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "das Nachthemd", HebrewWord: "כתונת לילה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Bademode", HebrewWord: "בגד ים", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Hausschuhe", HebrewWord: "נעלי בית", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 8, courseNameEnglish: "Basic Clothing", GermanWord: "die Schürze", HebrewWord: "סינר", knowlage: "X" , clerkUserId: userId },
// Common Food Items
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "das Brot", HebrewWord: "לחם", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "die Butter", HebrewWord: "חמאה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "die Milch", HebrewWord: "חלב", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "das Ei", HebrewWord: "ביצה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "der Käse", HebrewWord: "גבינה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "der Apfel", HebrewWord: "תפוח", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "die Banane", HebrewWord: "בננה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "die Orange", HebrewWord: "תפוז", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "die Kartoffel", HebrewWord: "תפוח אדמה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "die Tomate", HebrewWord: "עגבנייה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "die Gurke", HebrewWord: "מלפפון", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "der Salat", HebrewWord: "סלט", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "das Fleisch", HebrewWord: "בשר", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "der Fisch", HebrewWord: "דג", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "das Hähnchen", HebrewWord: "עוף", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "der Reis", HebrewWord: "אורז", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "die Nudeln", HebrewWord: "אטריות", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "das Salz", HebrewWord: "מלח", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "der Zucker", HebrewWord: "סוכר", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "der Honig", HebrewWord: "דבש", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "die Marmelade", HebrewWord: "ריבה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "die Schokolade", HebrewWord: "שוקולד", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "das Wasser", HebrewWord: "מים", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "der Saft", HebrewWord: "מיץ", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "das Bier", HebrewWord: "בירה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "der Wein", HebrewWord: "יין", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "der Kaffee", HebrewWord: "קפה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "der Tee", HebrewWord: "תה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "die Zwiebel", HebrewWord: "בצל", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 9, courseNameEnglish: "Common Food Items", GermanWord: "der Knoblauch", HebrewWord: "שום", knowlage: "V" , clerkUserId: userId },

// House Parts
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "das Wohnzimmer", HebrewWord: "סלון", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "das Schlafzimmer", HebrewWord: "חדר שינה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "die Küche", HebrewWord: "מטבח", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "das Badezimmer", HebrewWord: "חדר אמבטיה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "das Esszimmer", HebrewWord: "חדר אוכל", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "das Kinderzimmer", HebrewWord: "חדר ילדים", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "der Keller", HebrewWord: "מרתף", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "der Dachboden", HebrewWord: "עליית גג", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "der Flur", HebrewWord: "מסדרון", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "die Tür", HebrewWord: "דלת", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "das Fenster", HebrewWord: "חלון", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "der Garten", HebrewWord: "גן", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "der Balkon", HebrewWord: "מרפסת", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "die Treppe", HebrewWord: "מדרגות", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "das Dach", HebrewWord: "גג", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "die Wand", HebrewWord: "קיר", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "der Boden", HebrewWord: "רצפה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "die Decke", HebrewWord: "תקרה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "die Garage", HebrewWord: "מוסך", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "der Hof", HebrewWord: "חצר", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "die Haustür", HebrewWord: "דלת כניסה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "der Kamin", HebrewWord: "אח", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "die Veranda", HebrewWord: "מרפסת מקורה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "die Waschküche", HebrewWord: "חדר כביסה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "das Büro", HebrewWord: "משרד", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "die Terrasse", HebrewWord: "טרסה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "das Gästezimmer", HebrewWord: "חדר אורחים", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "die Vorratskammer", HebrewWord: "מזווה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "das Badezimmer", HebrewWord: "חדר שירותים", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 10, courseNameEnglish: "House Parts", GermanWord: "die Eingangshalle", HebrewWord: "אולם כניסה", knowlage: "V" , clerkUserId: userId },

// Animals
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "der Hund", HebrewWord: "כלב", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "die Katze", HebrewWord: "חתול", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "das Pferd", HebrewWord: "סוס", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "die Kuh", HebrewWord: "פרה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "das Schwein", HebrewWord: "חזיר", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "das Schaf", HebrewWord: "כבשה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "die Ziege", HebrewWord: "עז", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "der Hase", HebrewWord: "ארנב", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "der Fuchs", HebrewWord: "שועל", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "der Bär", HebrewWord: "דוב", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "der Löwe", HebrewWord: "אריה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "der Tiger", HebrewWord: "טיגריס", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "der Elefant", HebrewWord: "פיל", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "die Maus", HebrewWord: "עכבר", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "der Vogel", HebrewWord: "ציפור", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "der Fisch", HebrewWord: "דג", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "die Schlange", HebrewWord: "נחש", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "die Spinne", HebrewWord: "עכביש", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "der Affe", HebrewWord: "קוף", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "das Känguru", HebrewWord: "קנגורו", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "der Delfin", HebrewWord: "דולפין", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "der Wal", HebrewWord: "לוויתן", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "der Pinguin", HebrewWord: "פינגווין", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "das Krokodil", HebrewWord: "תנין", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "der Schmetterling", HebrewWord: "פרפר", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "die Ameise", HebrewWord: "נמלה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "die Biene", HebrewWord: "דבורה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "der Hahn", HebrewWord: "תרנגול", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "die Ente", HebrewWord: "ברווז", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 11, courseNameEnglish: "Animals", GermanWord: "die Gans", HebrewWord: "אווז", knowlage: "X" , clerkUserId: userId },

// Basic Emotions
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "glücklich", HebrewWord: "שמח", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "traurig", HebrewWord: "עצוב", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "wütend", HebrewWord: "כועס", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "aufgeregt", HebrewWord: "נרגש", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "ängstlich", HebrewWord: "מפוחד", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "zufrieden", HebrewWord: "מרוצה", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "überrascht", HebrewWord: "מופתע", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "gelangweilt", HebrewWord: "משועמם", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "besorgt", HebrewWord: "מודאג", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "verliebt", HebrewWord: "מאוהב", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "neidisch", HebrewWord: "מקנא", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "dankbar", HebrewWord: "מודה", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "müde", HebrewWord: "עייף", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "verärgert", HebrewWord: "כועס", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "schüchtern", HebrewWord: "ביישן", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "stolz", HebrewWord: "גאה", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "verwirrt", HebrewWord: "מבולבל", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "einsam", HebrewWord: "בודד", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "frustriert", HebrewWord: "מתוסכל", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "hoffnungsvoll", HebrewWord: "מקווה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "erschöpft", HebrewWord: "מותש", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "verletzt", HebrewWord: "נפגע", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "eifersüchtig", HebrewWord: "קנאי", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "beschämt", HebrewWord: "מתבייש", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "entspannt", HebrewWord: "רגוע", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "unwohl", HebrewWord: "לא בנוח", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "aufmerksam", HebrewWord: "קשוב", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "vergnügt", HebrewWord: "מרוצה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "hoffnungslos", HebrewWord: "חסר תקווה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מבוא", levelEnglish: "A1", courseId: 12, courseNameEnglish: "Basic Emotions", GermanWord: "erleichtert", HebrewWord: "מוקל", knowlage: "X" , clerkUserId: userId },

// A2
{ levelHebrew: "בסיסי", levelEnglish: "A2", courseId: 31, courseNameEnglish: "seasons", GermanWord: "sommer", HebrewWord: "קיץ", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "בסיסי", levelEnglish: "A2", courseId: 31, courseNameEnglish: "seasons", GermanWord: "winter", HebrewWord: "חורף", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "בסיסי", levelEnglish: "A2", courseId: 31, courseNameEnglish: "seasons", GermanWord: "herbst", HebrewWord: "סתיו", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "בסיסי", levelEnglish: "A2", courseId: 31, courseNameEnglish: "seasons", GermanWord: "frühling", HebrewWord: "אביב", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בסיסי", levelEnglish: "A2", courseId: 27, courseNameEnglish: "Shopping", GermanWord: "Apfel", HebrewWord: "תפוח", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בסיסי", levelEnglish: "A2", courseId: 27, courseNameEnglish: "Shopping", GermanWord: "Brot", HebrewWord: "לחם", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בסיסי", levelEnglish: "A2", courseId: 27, courseNameEnglish: "Shopping", GermanWord: "Milch", HebrewWord: "חלב", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בסיסי", levelEnglish: "A2", courseId: 27, courseNameEnglish: "Shopping", GermanWord: "Eier", HebrewWord: "ביצים", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "בסיסי", levelEnglish: "A2", courseId: 27, courseNameEnglish: "Shopping", GermanWord: "Käse", HebrewWord: "גבינה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "בסיסי", levelEnglish: "A2", courseId: 27, courseNameEnglish: "Shopping", GermanWord: "Butter", HebrewWord: "חמאה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "בסיסי", levelEnglish: "A2", courseId: 27, courseNameEnglish: "Shopping", GermanWord: "Fleisch", HebrewWord: "בשר", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "בסיסי", levelEnglish: "A2", courseId: 27, courseNameEnglish: "Shopping", GermanWord: "Gemüse", HebrewWord: "ירקות", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "בסיסי", levelEnglish: "A2", courseId: 27, courseNameEnglish: "Shopping", GermanWord: "Obst", HebrewWord: "פירות", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "בסיסי", levelEnglish: "A2", courseId: 27, courseNameEnglish: "Shopping", GermanWord: "Wasser", HebrewWord: "מים", knowlage: "X" , clerkUserId: userId },

// B1
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 59, courseNameEnglish: "News and media", GermanWord: "Zeitung", HebrewWord: "עיתון", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 59, courseNameEnglish: "News and media", GermanWord: "Nachrichten", HebrewWord: "חדשות", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 59, courseNameEnglish: "News and media", GermanWord: "Reporter", HebrewWord: "כתב", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 59, courseNameEnglish: "News and media", GermanWord: "Interview", HebrewWord: "ראיון", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 59, courseNameEnglish: "News and media", GermanWord: "Artikel", HebrewWord: "מאמר", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 59, courseNameEnglish: "News and media", GermanWord: "Fernsehen", HebrewWord: "טלוויזיה", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 59, courseNameEnglish: "News and media", GermanWord: "Radio", HebrewWord: "רדיו", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 59, courseNameEnglish: "News and media", GermanWord: "Überschrift", HebrewWord: "כותרת", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 59, courseNameEnglish: "News and media", GermanWord: "Online-Medien", HebrewWord: "מדיה מקוונת", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 59, courseNameEnglish: "News and media", GermanWord: "Nachrichtensprecher", HebrewWord: "מגיש חדשות", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 68, courseNameEnglish: "Nature and wildlife", GermanWord: "Baum", HebrewWord: "עץ", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 68, courseNameEnglish: "Nature and wildlife", GermanWord: "Fluss", HebrewWord: "נהר", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 68, courseNameEnglish: "Nature and wildlife", GermanWord: "Berg", HebrewWord: "הר", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 68, courseNameEnglish: "Nature and wildlife", GermanWord: "Wald", HebrewWord: "יער", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 68, courseNameEnglish: "Nature and wildlife", GermanWord: "See", HebrewWord: "אגם", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 68, courseNameEnglish: "Nature and wildlife", GermanWord: "Vogel", HebrewWord: "ציפור", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 68, courseNameEnglish: "Nature and wildlife", GermanWord: "Löwe", HebrewWord: "אריה", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 68, courseNameEnglish: "Nature and wildlife", GermanWord: "Fisch", HebrewWord: "דג", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 68, courseNameEnglish: "Nature and wildlife", GermanWord: "Blume", HebrewWord: "פרח", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "בינוני", levelEnglish: "B1", courseId: 68, courseNameEnglish: "Nature and wildlife", GermanWord: "Schmetterling", HebrewWord: "פרפר", knowlage: "?" , clerkUserId: userId },

// B2
{ levelHebrew: "מתקדם", levelEnglish: "B2", courseId: 68, courseNameEnglish: "Volunteerism and charity", GermanWord: "Freiwilliger", HebrewWord: "מתנדב", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מתקדם", levelEnglish: "B2", courseId: 68, courseNameEnglish: "Volunteerism and charity", GermanWord: "Spende", HebrewWord: "תרומה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מתקדם", levelEnglish: "B2", courseId: 68, courseNameEnglish: "Volunteerism and charity", GermanWord: "Organisation", HebrewWord: "ארגון", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מתקדם", levelEnglish: "B2", courseId: 68, courseNameEnglish: "Volunteerism and charity", GermanWord: "Hilfsprojekt", HebrewWord: "פרויקט סיוע", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מתקדם", levelEnglish: "B2", courseId: 68, courseNameEnglish: "Volunteerism and charity", GermanWord: "Mitgefühl", HebrewWord: "אמפתיה", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מתקדם", levelEnglish: "B2", courseId: 68, courseNameEnglish: "Volunteerism and charity", GermanWord: "Fundraising", HebrewWord: "גיוס כספים", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מתקדם", levelEnglish: "B2", courseId: 68, courseNameEnglish: "Volunteerism and charity", GermanWord: "Gemeinschaft", HebrewWord: "קהילה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מתקדם", levelEnglish: "B2", courseId: 68, courseNameEnglish: "Volunteerism and charity", GermanWord: "Ehrenamt", HebrewWord: "התנדבות", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מתקדם", levelEnglish: "B2", courseId: 68, courseNameEnglish: "Volunteerism and charity", GermanWord: "Wohltätigkeit", HebrewWord: "צדקה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מתקדם", levelEnglish: "B2", courseId: 68, courseNameEnglish: "Volunteerism and charity", GermanWord: "Nächstenliebe", HebrewWord: "אהבת הזולת", knowlage: "X" , clerkUserId: userId },

// C1
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 118, courseNameEnglish: "Human rights issues", GermanWord: "Menschenrechte", HebrewWord: "זכויות אדם", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 118, courseNameEnglish: "Human rights issues", GermanWord: "Gerechtigkeit", HebrewWord: "צדק", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 118, courseNameEnglish: "Human rights issues", GermanWord: "Freiheit", HebrewWord: "חירות", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 118, courseNameEnglish: "Human rights issues", GermanWord: "Diskriminierung", HebrewWord: "אפליה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 118, courseNameEnglish: "Human rights issues", GermanWord: "Asyl", HebrewWord: "מקלט", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 118, courseNameEnglish: "Human rights issues", GermanWord: "Gleichheit", HebrewWord: "שוויון", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 118, courseNameEnglish: "Human rights issues", GermanWord: "Unterdrückung", HebrewWord: "דיכוי", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 118, courseNameEnglish: "Human rights issues", GermanWord: "Kinderarbeit", HebrewWord: "עבודת ילדים", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 118, courseNameEnglish: "Human rights issues", GermanWord: "Meinungsfreiheit", HebrewWord: "חופש הביטוי", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 118, courseNameEnglish: "Human rights issues", GermanWord: "Toleranz", HebrewWord: "סובלנות", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 122, courseNameEnglish: "Space exploration", GermanWord: "Weltraum", HebrewWord: "חלל", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 122, courseNameEnglish: "Space exploration", GermanWord: "Rakete", HebrewWord: "רקטה", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 122, courseNameEnglish: "Space exploration", GermanWord: "Astronaut", HebrewWord: "אסטרונאוט", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 122, courseNameEnglish: "Space exploration", GermanWord: "Erde", HebrewWord: "כדור הארץ", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 122, courseNameEnglish: "Space exploration", GermanWord: "Mond", HebrewWord: "ירח", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 122, courseNameEnglish: "Space exploration", GermanWord: "Stern", HebrewWord: "כוכב", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 122, courseNameEnglish: "Space exploration", GermanWord: "Raumschiff", HebrewWord: "חללית", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 122, courseNameEnglish: "Space exploration", GermanWord: "Sonne", HebrewWord: "שמש", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 122, courseNameEnglish: "Space exploration", GermanWord: "Planeten", HebrewWord: "כוכבי לכת", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "מתקדם מאוד", levelEnglish: "C1", courseId: 122, courseNameEnglish: "Space exploration", GermanWord: "Universum", HebrewWord: "יקום", knowlage: "?" , clerkUserId: userId },

// C2
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Gehirn", HebrewWord: "מוח", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Neuron", HebrewWord: "נוירון", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Synapse", HebrewWord: "סינפסה", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Nervensystem", HebrewWord: "מערכת העצבים", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Gedächtnis", HebrewWord: "זיכרון", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Emotion", HebrewWord: "רגש", knowlage: "X" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Hirnrinde", HebrewWord: "קליפת המוח", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Refle?", HebrewWord: "רפלקס", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Motorik", HebrewWord: "מוטוריקה", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Bewusstsein", HebrewWord: "מודעות", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Kognition", HebrewWord: "קוגניציה", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Dopamin", HebrewWord: "דופמין", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Hippocampus", HebrewWord: "היפוקמפוס", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Neurotransmitter", HebrewWord: "מוליך עצבי", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Plastizität", HebrewWord: "פלסטיות", knowlage: "?" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Stress", HebrewWord: "לחץ", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Sensorik", HebrewWord: "חישה", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Verarbeitung", HebrewWord: "עיבוד", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Impuls", HebrewWord: "דחף", knowlage: "V" , clerkUserId: userId },
{ levelHebrew: "שפת אם", levelEnglish: "C2", courseId: 130, courseNameEnglish: "Neuroscience", GermanWord: "Perzeption", HebrewWord: "תפיסה", knowlage: "V" , clerkUserId: userId },
  ]).returning({ id: Words.id });
}

seed();