import { CourseNames } from "../../drizzle/schema";
import { db } from "../../drizzle/db";
import { Course } from "../../types/seedersType";
import { CourseLangauge } from "../../types/seedersType";

export const courseSeeder = async (userId: string, courseIds: Array<{ index: number; uuid: string; courseName: string }>) => {
  const courses: Course[] = 
  [ 
    // A1
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Colors", courseNameGerman: "Farben", courseNameHebrew: "צבעים", lessonCompleted: 0 },
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Numbers", courseNameGerman: "Zahlen", courseNameHebrew: "מספרים", lessonCompleted: 0 },
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Family Members", courseNameGerman: "Familienmitglieder", courseNameHebrew: "בני משפחה", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Days of the Week", courseNameGerman: "Wochentage", courseNameHebrew: "ימי השבוע", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Months", courseNameGerman: "Monate", courseNameHebrew: "חודשים", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Introduction", courseNameGerman: "Einführung", courseNameHebrew: "היכרות", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Weather", courseNameGerman: "Wetter", courseNameHebrew: "מזג אוויר", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Clothes", courseNameGerman: "Kleidung", courseNameHebrew: "בגדים", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Food Products", courseNameGerman: "Lebensmittel", courseNameHebrew: "מוצרי מזון"     , lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Beverages", courseNameGerman: "Getränke", courseNameHebrew: "מוצרי שתייה", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Parts of the House", courseNameGerman: "Teile des Hauses", courseNameHebrew: "חלקי הבית", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Animals", courseNameGerman: "Tiere", courseNameHebrew: "חיות", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Emotions", courseNameGerman: "Emotionen", courseNameHebrew: "רגשות", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Transportation", courseNameGerman: "Transport", courseNameHebrew: "תחבורה"     , lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "School Supplies", courseNameGerman: "Schulmaterial", courseNameHebrew: "ציוד לבית ספר", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Professions", courseNameGerman: "Berufe", courseNameHebrew: "מקצועות", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Body Parts", courseNameGerman: "Körperteile", courseNameHebrew: "חלקי גוף", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Hobbies", courseNameGerman: "Hobbys", courseNameHebrew: "תחביבים", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Furniture", courseNameGerman: "Möbel", courseNameHebrew: "רהיטים", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Sports", courseNameGerman: "Sportarten", courseNameHebrew: "ספורט", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Shapes", courseNameGerman: "Formen", courseNameHebrew: "צורות", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Time", courseNameGerman: "Zeit", courseNameHebrew: "זמן", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Common Actions", courseNameGerman: "Häufige Aktionen", courseNameHebrew: "פעולות נפוצות", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Shopping", courseNameGerman: "Einkaufen", courseNameHebrew: "קניות", lessonCompleted: 0 }, 
    { englishLevel: "A1", hebrewLevel: "מבוא", courseNameEnglish: "Technology", courseNameGerman: "Technologie", courseNameHebrew: "טכנולוגיה", lessonCompleted: 0 }, 

    // A2
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Health and Fitness", courseNameGerman: "Gesundheit und Fitness", courseNameHebrew: "בריאות וכושר", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Intermediate Clothes", courseNameGerman: "Kleidung Mittelstufe", courseNameHebrew: "בגדים בינוני", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Intermediate Animals", courseNameGerman: "Tiere Mittelstufe", courseNameHebrew: "חיות בינוני", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Holidays", courseNameGerman: "Feiertage", courseNameHebrew: "חגים", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Intermediate Numbers", courseNameGerman: "Zahlen Mittelstufe", courseNameHebrew: "מספרים בינוני", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Countries", courseNameGerman: "Jahreszeiten", courseNameHebrew: "עונות השנה", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Intermediate Body Parts", courseNameGerman: "Körperteile Mittelstufe", courseNameHebrew: "חלקי גוף בינוני", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Health", courseNameGerman: "Gesundheit", courseNameHebrew: "בריאות", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Directions", courseNameGerman: "Richtungen", courseNameHebrew: "כיוונים", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Means of Communication", courseNameGerman: "Kommunikationsmittel", courseNameHebrew: "אמצעי תקשורת", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Intermediate Furniture", courseNameGerman: "Möbel Mittelstufe", courseNameHebrew: "רהיטים בינוני", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Intermediate Weather", courseNameGerman: "Wetter Mittelstufe", courseNameHebrew: "מזג אוויר בינוני", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Kitchen Tools", courseNameGerman: "Küchenutensilien", courseNameHebrew: "כלי מטבח", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Musical Instruments", courseNameGerman: "Musikinstrumente", courseNameHebrew: "כלי נגינה", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Economic Terms", courseNameGerman: "Wirtschaftsbegriffe", courseNameHebrew: "מונחים כלכליים", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Social Media", courseNameGerman: "Soziale Medien", courseNameHebrew: "מדיה חברתית", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Intermediate Introduction", courseNameGerman: "Einführung Mittelstufe", courseNameHebrew: "היכרות בינוני", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Education", courseNameGerman: "Bildung", courseNameHebrew: "חינוך", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "City and Village", courseNameGerman: "Stadt und Dorf", courseNameHebrew: "עיר וכפר", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Intermediate Technology", courseNameGerman: "Technologie Mittelstufe", courseNameHebrew: "טכנולוגיה בינוני", lessonCompleted: 0 },
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Recycling", courseNameGerman: "Recycling", courseNameHebrew: "מחזור", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Intermediate Hobbies", courseNameGerman: "Hobbys Mittelstufe", courseNameHebrew: "תחביבים בינוני", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Politics", courseNameGerman: "Politik", courseNameHebrew: "פוליטיקה", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Intermediate Family Members", courseNameGerman: "Familienmitglieder Mittelstufe", courseNameHebrew: "בני משפחה בינוני", lessonCompleted: 0 }, 
    { englishLevel: "A2", hebrewLevel: "בסיסי", courseNameEnglish: "Intermediate Shopping", courseNameGerman: "Einkaufen Mittelstufe", courseNameHebrew: "קניות בינוני", lessonCompleted: 0 },  

    // B1
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Intermediate Colors", courseNameGerman: "Farben Mittelstufe", courseNameHebrew: "צבעים בינוני", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Advanced Animals", courseNameGerman: "Tiere Fortgeschritten", courseNameHebrew: "חיות מתקדם", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Cultural Diversity", courseNameGerman: "Kulturelle Vielfalt", courseNameHebrew: "גיוון תרבותי", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Intermediate Professions", courseNameGerman: "Berufe Mittelstufe", courseNameHebrew: "מקצועות בינוני", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Intermediate Politics", courseNameGerman: "Politik Mittelstufe", courseNameHebrew: "פוליטיקה בינוני", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Intermediate Economic Terms", courseNameGerman: "Wirtschaftsbegriffe Mittelstufe", courseNameHebrew: "מונחים כלכליים בינוני", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Climate Change", courseNameGerman: "Klimawandel", courseNameHebrew: "שינויי אקלים", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Intermediate Transportation", courseNameGerman: "Transport Mittelstufe", courseNameHebrew: "תחבורה בינוני", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Science", courseNameGerman: "Wissenschaft", courseNameHebrew: "מדע", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Social Issues", courseNameGerman: "Soziale Probleme", courseNameHebrew: "בעיות חברתיות", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Intermediate Sports", courseNameGerman: "Sportarten Mittelstufe", courseNameHebrew: "ספורט בינוני", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Higher Education", courseNameGerman: "Höhere Bildung", courseNameHebrew: "השכלה גבוהה", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Competitions", courseNameGerman: "Wettbewerbe", courseNameHebrew: "תחרויות", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Intermediate Food Products", courseNameGerman: "Lebensmittel Mittelstufe", courseNameHebrew: "מוצרי מזון בינוני", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Adventures", courseNameGerman: "Abenteuer", courseNameHebrew: "הרפתקאות", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Work", courseNameGerman: "Arbeit", courseNameHebrew: "עבודה", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Intermediate Emotions", courseNameGerman: "Emotionen Mittelstufe", courseNameHebrew: "רגשות בינוני", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Intermediate Kitchen Tools", courseNameGerman: "Küchenutensilien Mittelstufe", courseNameHebrew: "כלי מטבח בינוני", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Numbers by Tens", courseNameGerman: "Zahlen nach Zehnern)", courseNameHebrew: "מספרים עשרות", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Advanced Weather", courseNameGerman: "Wetter Fortgeschritten", courseNameHebrew: "מזג אוויר מתקדם", lessonCompleted: 0 },  
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Intermediate Shapes", courseNameGerman: "Formen Mittelstufe", courseNameHebrew: "צורות בינוני", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Intermediate Directions", courseNameGerman: "Richtungen Mittelstufe", courseNameHebrew: "כיוונים בינוני", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Intermediate Beverages", courseNameGerman: "Getränke", courseNameHebrew: "מוצרי שתייה", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Intermediate Musical Instruments", courseNameGerman: "Musikinstrumente Mittelstufe", courseNameHebrew: "כלי נגינה בינוני", lessonCompleted: 0 }, 
    { englishLevel: "B1", hebrewLevel: "בינוני", courseNameEnglish: "Intermediate Education", courseNameGerman: "Bildung Mittelstufe", courseNameHebrew: "חינוך בינוני", lessonCompleted: 0 },  
    
      // B2
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Advanced Colors", courseNameGerman: "Farben Fortgeschritten", courseNameHebrew: "צבעים מתקדם", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Advanced Clothes", courseNameGerman: "Kleidung Fortgeschritten", courseNameHebrew: "בגדים מתקדם", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Intermediate School Supplies", courseNameGerman: "Schulmaterial Mittelstufe", courseNameHebrew: "ציוד לבית ספר בינוני", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Intermediate Health", courseNameGerman: "Gesundheit Mittelstufe", courseNameHebrew: "בריאות בינוני", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Intermediate Days of the Week", courseNameGerman: "Wochentage Mittelstufe", courseNameHebrew: "ימי השבוע בינוני", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Taxes", courseNameGerman: "Steuern", courseNameHebrew: "מיסים", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Philosophical Topics", courseNameGerman: "Philosophische Themen", courseNameHebrew: "נושאים בפילוסופיה", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Intermediate Parts of the House", courseNameGerman: "Teile des Hauses Mittelstufe", courseNameHebrew: "חלקי הבית בינוני", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Describing People", courseNameGerman: "Menschen Beschreiben", courseNameHebrew: "תיאור אנשים", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Crypto", courseNameGerman: "Krypto", courseNameHebrew: "קריפטו", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Advanced Politics", courseNameGerman: "Politik Fortgeschritten", courseNameHebrew: "פוליטיקה מתקדם", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "International Relations", courseNameGerman: "Internationale Beziehungen", courseNameHebrew: "יחסים בינלאומיים", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Stars", courseNameGerman: "Sterne", courseNameHebrew: "כוכבים", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Theatre", courseNameGerman: "Theater", courseNameHebrew: "תיאטרון", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Human Rights", courseNameGerman: "Menschenrechte", courseNameHebrew: "זכויות אדם", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Chemistry", courseNameGerman: "Chemie", courseNameHebrew: "כימיה", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Artificial Intelligence", courseNameGerman: "Künstliche Intelligenz", courseNameHebrew: "בינה מלאכותית", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Intermediate Holidays", courseNameGerman: "Feiertage Mittelstufe", courseNameHebrew: "חגים בינוני", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Numbers by Hundreds", courseNameGerman: "Zahlen nach Hunderten", courseNameHebrew: "מספרים מאות", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Numbers by Thousands", courseNameGerman: "Zahlen nach Tausendern", courseNameHebrew: "מספרים אלפים", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Mathematical Topics", courseNameGerman: "Mathematische Themen", courseNameHebrew: "נושאים מתמטיים", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Intermediate Higher Education", courseNameGerman: "Höhere Bildung Mittelstufe", courseNameHebrew: "השכלה גבוהה בינוני", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Biology", courseNameGerman: "Biologie", courseNameHebrew: "ביולוגיה", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Intermediate Work", courseNameGerman: "Arbeit Mittelstufe", courseNameHebrew: "עבודה בינוני", lessonCompleted: 0 }, 
      { englishLevel: "B2", hebrewLevel: "מתקדם", courseNameEnglish: "Advanced Emotions", courseNameGerman: "Emotionen Fortgeschritten", courseNameHebrew: "רגשות מתקדם", lessonCompleted: 0 }, 

      // C1
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Digital Marketing", courseNameGerman: "Digitales Marketing", courseNameHebrew: "שיווק דיגיטלי", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Intermediate Countries", courseNameGerman: "Grafikdesign", courseNameHebrew: "עיצוב גרפי", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Graphic Design", courseNameGerman: "Grafikdesign", courseNameHebrew: "עיצוב גרפי", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Classical Music", courseNameGerman: "Klassische Musik", courseNameHebrew: "מוזיקה קלאסית", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Museums", courseNameGerman: "Museen", courseNameHebrew: "מוזיאונים", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Stock Market", courseNameGerman: "Aktienmarkt", courseNameHebrew: "שוק ההון", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Cooking", courseNameGerman: "Kochen", courseNameHebrew: "בישול", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Robots", courseNameGerman: "Roboter", courseNameHebrew: "רובוטים", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Services", courseNameGerman: "Dienstleistungen", courseNameHebrew: "שירותים", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Christmas", courseNameGerman: "Weihnachten", courseNameHebrew: "כריסמס", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Fruits", courseNameGerman: "Früchte", courseNameHebrew: "פירות", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Vegetables", courseNameGerman: "Gemüse", courseNameHebrew: "ירקות", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Makeup", courseNameGerman: "Make-up", courseNameHebrew: "איפור", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Advanced Countries", courseNameGerman: "Länder", courseNameHebrew: "מדינות", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Extreme Sports", courseNameGerman: "Extremsportarten", courseNameHebrew: "ספורט אתגרי", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Surfing", courseNameGerman: "Surfen", courseNameHebrew: "גלישה", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Camping", courseNameGerman: "Camping", courseNameHebrew: "קמפינג", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Martial Arts", courseNameGerman: "Kampfkünste", courseNameHebrew: "אומנויות לחימה", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Market", courseNameGerman: "Markt", courseNameHebrew: "שוק", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Gifts", courseNameGerman: "Geschenke", courseNameHebrew: "מתנות", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Restaurant", courseNameGerman: "Restaurant", courseNameHebrew: "מסעדה", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Bank", courseNameGerman: "Bank", courseNameHebrew: "בנק", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "News", courseNameGerman: "Nachrichten", courseNameHebrew: "חדשות", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Writing Tools", courseNameGerman: "Schreibwerkzeuge", courseNameHebrew: "כלי כתיבה", lessonCompleted: 0 },
      { englishLevel: "C1", hebrewLevel: "מתקדם מאוד", courseNameEnglish: "Tools", courseNameGerman: "Fortgeschrittene Werkzeuge", courseNameHebrew: "כלי עבודה מתקדם", lessonCompleted: 0 },
  
    // C2
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Business Communication", courseNameGerman: "Geschäftskommunikation", courseNameHebrew: "תקשורת עסקית", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Cyber", courseNameGerman: "Cyber", courseNameHebrew: "סייבר", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Academic Writing", courseNameGerman: "Akademisches Schreiben", courseNameHebrew: "כתיבה אקדמית", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Leadership and Management", courseNameGerman: "Führung und Management", courseNameHebrew: "מנהיגות וניהול", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Legal Terms", courseNameGerman: "Rechtliche Begriffe", courseNameHebrew: "מונחים משפטיים", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Globalization", courseNameGerman: "Globalisierung", courseNameHebrew: "גלובליזציה", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Topics in Psychology", courseNameGerman: "Themen in der Psychologie", courseNameHebrew: "נושאים בפסיכולוגיה", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Renewable Energy", courseNameGerman: "Erneuerbare Energien", courseNameHebrew: "אנרגיה מתחדשת", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Neuroscience", courseNameGerman: "Neurowissenschaft", courseNameHebrew: "מדעי המוח", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Topics in Physics", courseNameGerman: "Themen in der Physik", courseNameHebrew: "נושאים בפיזיקה", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Topics in Architecture", courseNameGerman: "Themen in der Architektur", courseNameHebrew: "נושאים באדריכלות", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Religions", courseNameGerman: "Religionen", courseNameHebrew: "דתות", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Advanced Tools", courseNameGerman: "Werkzeuge", courseNameHebrew: "כלי עבודה", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Plants and Flowers", courseNameGerman: "Pflanzen und Blumen", courseNameHebrew: "צמחים ופרחים", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Sea", courseNameGerman: "Meer", courseNameHebrew: "ים", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Office Supplies", courseNameGerman: "Bürobedarf", courseNameHebrew: "כלים משרדיים", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Advanced Conversation Management", courseNameGerman: "Fortgeschrittenes Gesprächsmanagement", courseNameHebrew: "ניהול שיחה מתקדם", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Nature Trip", courseNameGerman: "Naturausflug", courseNameHebrew: "טיול בטבע", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Cars", courseNameGerman: "Autos", courseNameHebrew: "מכוניות", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Houses", courseNameGerman: "Häuser", courseNameHebrew: "בתים", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Gym", courseNameGerman: "Fitnessstudio", courseNameHebrew: "חדר כושר", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Brain Research", courseNameGerman: "Hirnforschung", courseNameHebrew: "חקר המוח", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Army", courseNameGerman: "Armee", courseNameHebrew: "צבא", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Cinema", courseNameGerman: "Kino", courseNameHebrew: "בית קולנוע", lessonCompleted: 0 },
    { englishLevel: "C2", hebrewLevel: "שפת אם", courseNameEnglish: "Intermediate Extreme Sports", courseNameGerman: "Extremsportarten", courseNameHebrew: "ספורט אתגרי", lessonCompleted: 0 }
  ];

const languages = [
  CourseLangauge.German,
  CourseLangauge.Italian,
  CourseLangauge.Spanish,
  CourseLangauge.French,
  CourseLangauge.English
];

const requiredLength = courses.length * languages.length;
if (courseIds.length < requiredLength) {
  throw new Error(`Insufficient courseIds provided. Expected ${requiredLength}, but got ${courseIds.length}.`);
}

const courseData = courses.flatMap((course, courseIndex) =>
  languages.map((language, langIndex) => ({
    ...course,
    userId,
    courseId: courseIds[courseIndex * languages.length + langIndex].uuid,
    language,
    courseOrder: courseIndex + 1,
  }))
);

await db.insert(CourseNames).values(courseData).returning();
};