import { CourseNames } from "../../drizzle/schema";
import { db } from "../../drizzle/db";
import { Course } from "../type/seedersType";

export const courseSeeder = async (userId: string, courseIds: Array<{ index: number; uuid: string; courseName: string }>) => {
  const courses: Course[] = [
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Colors", courseNameGerman: "Farben", courseNameHebrew: "צבעים", lessonCompleted: 6 },
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Numbers", courseNameGerman: "Zahlen", courseNameHebrew: "מספרים", lessonCompleted: 6 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Family members", courseNameGerman: "Familienmitglieder", courseNameHebrew: "בני משפחה", lessonCompleted: 6 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Days of the week", courseNameGerman: "Wochentage", courseNameHebrew: "ימי השבוע", lessonCompleted: 6 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Months", courseNameGerman: "Monate", courseNameHebrew: "חודשים", lessonCompleted: 6 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Greetings", courseNameGerman: "Grüße", courseNameHebrew: "ברכות", lessonCompleted: 1 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Weather", courseNameGerman: "Wetter", courseNameHebrew: "מזג האוויר", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Basic clothing", courseNameGerman: "Grundkleidung", courseNameHebrew: "בגדים בסיסיים", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Common food items", courseNameGerman: "Häufige Lebensmittel", courseNameHebrew: "מוצרי מזון נפוצים", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "House parts", courseNameGerman: "Hausteile", courseNameHebrew: "חלקי הבית", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Animals", courseNameGerman: "Tiere", courseNameHebrew: "חיות", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Basic emotions", courseNameGerman: "Grundgefühle", courseNameHebrew: "רגשות בסיסיות", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Transportation", courseNameGerman: "Transport", courseNameHebrew: "הובלה", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "School supplies", courseNameGerman: "Schulmaterial", courseNameHebrew: "ציודי בית הספר", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Professions", courseNameGerman: "Berufe", courseNameHebrew: "מקצועות", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Body parts", courseNameGerman: "Körperteile", courseNameHebrew: "חלקי הגוף", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Hobbies", courseNameGerman: "Hobbys", courseNameHebrew: "תחביבים", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Basic furniture", courseNameGerman: "Grundmöbel", courseNameHebrew: "רהיט בסיסיים", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Sports", courseNameGerman: "Sportarten", courseNameHebrew: "ספורט", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Shapes", courseNameGerman: "Formen", courseNameHebrew: "צורות", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Time", courseNameGerman: "Zeit", courseNameHebrew: "זמן", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Common places", courseNameGerman: "Gemeinsame Orte", courseNameHebrew: "מקומות נפוצות", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Festivals", courseNameGerman: "Feste", courseNameHebrew: "חגיגים", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Common actions", courseNameGerman: "Häufige Aktionen", courseNameHebrew: "פעולות נפוצות", lessonCompleted: 0 }, 
    { englishLevel: "A1" as const, hebrewLevel: "מבוא" as const, courseNameEnglish: "Technology basics", courseNameGerman: "Technologie Grundlagen", courseNameHebrew: "טכנולוגיה בסיסית", lessonCompleted: 0 }, 
  
    // A2
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Travel and transportation", courseNameGerman: "Reisen und Transport", courseNameHebrew: "נסיעות והובלה", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Shopping", courseNameGerman: "Einkaufen", courseNameHebrew: "קניות", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Food and drinks (advanced)", courseNameGerman: "Lebensmittel und Getränke (fortgeschritten)", courseNameHebrew: "מזון ומשקאות (מתקדם)", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Personal hygiene items", courseNameGerman: "Körperpflegeprodukte", courseNameHebrew: "מוצרי היגיינה אישית", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Holidays and traditions", courseNameGerman: "Feiertage und Traditionen", courseNameHebrew: "חגים ומסורת", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Seasons", courseNameGerman: "Jahreszeiten", courseNameHebrew: "עונות השנה", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Basic health", courseNameGerman: "Grundlegende Gesundheit", courseNameHebrew: "בריאות בריאות", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Daily routines", courseNameGerman: "Tagesabläufe", courseNameHebrew: "שגרות יומיות", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Public places", courseNameGerman: "Öffentliche Orte", courseNameHebrew: "מקומות ציבוריות", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Directions and locations", courseNameGerman: "Richtungen und Standorte", courseNameHebrew: "כיוונים ומיקומים", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Modes of communication", courseNameGerman: "Kommunikationsmittel", courseNameHebrew: "אמצעי תקשורת", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Types of entertainment", courseNameGerman: "Unterhaltungsarten", courseNameHebrew: "סוגיות בידור", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Simple adjectives", courseNameGerman: "Einfache Adjektive", courseNameHebrew: "תארים פשוטים", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Family occasions", courseNameGerman: "Familienanlässe", courseNameHebrew: "אירועי משפחה", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Simple weather terms", courseNameGerman: "Einfache Wetterbegriffe", courseNameHebrew: "מונחים פשוטים על מזג אוויר", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "School subjects", courseNameGerman: "Schulfächer", courseNameHebrew: "תמודות בבית הספר", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Basic verbs in context", courseNameGerman: "Grundlegende Verben im Kontext", courseNameHebrew: "פעלים בסיסיים המתאמים", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Pets and farm animals", courseNameGerman: "Haustiere und Nutztiere", courseNameHebrew: "חיות משק ובעלי משק", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Weekend activities", courseNameGerman: "Wochenendaktivitäten", courseNameHebrew: "פעילות לסופשים", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Cultural landmarks", courseNameGerman: "Kulturelle Wahrzeichen", courseNameHebrew: "אתרי תרבות", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Tools and utensils", courseNameGerman: "Werkzeuge und Utensilien", courseNameHebrew: "כליים וכלי מטבח", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Basic emotions and feelings", courseNameGerman: "Grundlegende Emotionen und Gefühle", courseNameHebrew: "רגשות בסיסיות", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Street signs and warnings", courseNameGerman: "Straßenschilder und Warnungen", courseNameHebrew: "שילוטי בעלים ואזרות", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Simple financial terms", courseNameGerman: "Einfache Finanzbegriffe", courseNameHebrew: "מונחים כלכליים פשוטים", lessonCompleted: 0 }, 
    { englishLevel: "A2" as const, hebrewLevel: "בסיסי" as const, courseNameEnglish: "Music and instruments", courseNameGerman: "Musik und Instrumente", courseNameHebrew: "מוזיקה וכליי נגינה", lessonCompleted: 0 }, 
  
  
    // B1
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Work and jobs", courseNameGerman: "Arbeit und Berufe", courseNameHebrew: "עבודה ומקצועות", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Social media and online platforms", courseNameGerman: "Soziale Medien und Online-Plattformen", courseNameHebrew: "מדיה חברתית ופלטפורמות מקוונות", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Health and fitness", courseNameGerman: "Gesundheit und Fitness", courseNameHebrew: "בריאות וכושר", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Environment and recycling", courseNameGerman: "Umwelt und Recycling", courseNameHebrew: "סביבה ומיחזור", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Technology and gadgets", courseNameGerman: "Technologie und Geräte", courseNameHebrew: "טכנולוגיה וגאדג'טים", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Travel and holidays", courseNameGerman: "Reisen und Ferien", courseNameHebrew: "נסיעות וחופשות", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Education and study habits", courseNameGerman: "Bildung und Lerngewohnheiten", courseNameHebrew: "חינוך והרגלי לימוד", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Cultural diversity", courseNameGerman: "Kulturelle Vielfalt", courseNameHebrew: "גיוון תרבותי", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "News and media", courseNameGerman: "Nachrichten und Medien", courseNameHebrew: "חדשות ומדיה", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Describing people", courseNameGerman: "Menschen beschreiben", courseNameHebrew: "תיאור אנשים", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Celebrations and events", courseNameGerman: "Feiern und Veranstaltungen", courseNameHebrew: "חגיגות ואירועים", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Hobbies and leisure activities", courseNameGerman: "Hobbys und Freizeitaktivitäten", courseNameHebrew: "תחביבים ופעילויות פנאי", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Relationships and friendship", courseNameGerman: "Beziehungen und Freundschaft", courseNameHebrew: "מערכות יחסים וחברות", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "City life and countryside", courseNameGerman: "Stadtleben und Land", courseNameHebrew: "חיי עיר וכפר", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Basic politics and government terms", courseNameGerman: "Grundlagen der Politik und Regierung", courseNameHebrew: "מונחים בסיסיים בפוליטיקה וממשל", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Transportation systems", courseNameGerman: "Verkehrssysteme", courseNameHebrew: "מערכות תחבורה", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Historical events", courseNameGerman: "Historische Ereignisse", courseNameHebrew: "אירועים היסטוריים", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Nature and wildlife", courseNameGerman: "Natur und Wildtiere", courseNameHebrew: "טבע וחיות בר", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Fashion and trends", courseNameGerman: "Mode und Trends", courseNameHebrew: "אופנה וטרנדים", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Stress management", courseNameGerman: "Stressbewältigung", courseNameHebrew: "ניהול מתח", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Problem-solving scenarios", courseNameGerman: "Problemlösungs-Szenarien", courseNameHebrew: "תרחישי פתרון בעיות", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Describing feelings and thoughts", courseNameGerman: "Gefühle und Gedanken beschreiben", courseNameHebrew: "תיאור רגשות ומחשבות", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Fiction and literature genres", courseNameGerman: "Fiktion und Literaturgenres", courseNameHebrew: "ז'אנרים בספרות ובדמיון", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Scientific discoveries", courseNameGerman: "Wissenschaftliche Entdeckungen", courseNameHebrew: "תגליות מדעיות", lessonCompleted: 0 }, 
    { englishLevel: "B1" as const, hebrewLevel: "בינוני" as const, courseNameEnglish: "Food culture around the world", courseNameGerman: "Esskultur weltweit", courseNameHebrew: "תרבות אוכל מסביב לעולם", lessonCompleted: 0 }, 
  
  
      // B2
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Advanced travel (backpacking, ecotourism)", courseNameGerman: "Fortgeschrittenes Reisen (Rucksackreisen, Ökotourismus)", courseNameHebrew: "נסיעות מתקדמות (טיולים עם תרמיל, תיירות אקולוגית)", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Economy and finance basics", courseNameGerman: "Grundlagen der Wirtschaft und Finanzen", courseNameHebrew: "יסודות הכלכלה והפיננסים", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Global warming and climate change", courseNameGerman: "Globale Erwärmung und Klimawandel", courseNameHebrew: "התחממות כדור הארץ ושינויי אקלים", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Technology advancements", courseNameGerman: "Technologische Fortschritte", courseNameHebrew: "התפתחויות טכנולוגיות", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Social issues (homelessness, inequality)", courseNameGerman: "Soziale Probleme (Obdachlosigkeit, Ungleichheit)", courseNameHebrew: "בעיות חברתיות (חוסר בית, אי שוויון)", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Volunteerism and charity", courseNameGerman: "Ehrenamt und Wohltätigkeit", courseNameHebrew: "התנדבות וצדקה", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Science and research topics", courseNameGerman: "Wissenschaft und Forschungsthemen", courseNameHebrew: "מדע ונושאי מחקר", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Advanced education topics (higher education)", courseNameGerman: "Fortgeschrittene Bildungsthemen (Hochschulbildung)", courseNameHebrew: "נושאי חינוך מתקדמים (השכלה גבוהה)", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Historical figures and their contributions", courseNameGerman: "Historische Persönlichkeiten und ihre Beiträge", courseNameHebrew: "דמויות היסטוריות ותרומותיהן", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Advanced personal development", courseNameGerman: "Fortgeschrittene persönliche Entwicklung", courseNameHebrew: "התפתחות אישית מתקדמת", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Sports and international competitions", courseNameGerman: "Sport und internationale Wettbewerbe", courseNameHebrew: "ספורט ותחרויות בינלאומיות", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Art and exhibitions", courseNameGerman: "Kunst und Ausstellungen", courseNameHebrew: "אמנות ותערוכות", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Debating topics", courseNameGerman: "Debattenthemen", courseNameHebrew: "נושאי ויכוח", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Ethical dilemmas", courseNameGerman: "Ethische Dilemmata", courseNameHebrew: "דילמות אתיות", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Public speaking", courseNameGerman: "Öffentliches Reden", courseNameHebrew: "דיבור בפני קהל", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Philosophical questions", courseNameGerman: "Philosophische Fragen", courseNameHebrew: "שאלות פילוסופיות", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Innovations in healthcare", courseNameGerman: "Innovationen im Gesundheitswesen", courseNameHebrew: "חידושים בתחום הבריאות", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Adventure and survival skills", courseNameGerman: "Abenteuer- und Überlebensfähigkeiten", courseNameHebrew: "הרפתקאות וכישורי הישרדות", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Advanced emotions and psychology", courseNameGerman: "Fortgeschrittene Emotionen und Psychologie", courseNameHebrew: "רגשות מתקדמים ופסיכולוגיה", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Networking and communication skills", courseNameGerman: "Netzwerk- und Kommunikationsfähigkeiten", courseNameHebrew: "כישורי רשת ותקשורת", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Freelancing and entrepreneurship", courseNameGerman: "Freiberuflichkeit und Unternehmertum", courseNameHebrew: "עבודה כפרילנס ויזמות", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Media and propaganda", courseNameGerman: "Medien und Propaganda", courseNameHebrew: "מדיה ותעמולה", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Artificial intelligence", courseNameGerman: "Künstliche Intelligenz", courseNameHebrew: "בינה מלאכותית", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Fictional storytelling", courseNameGerman: "Fiktionales Erzählen", courseNameHebrew: "סיפורת בדיונית", lessonCompleted: 0 }, 
      { englishLevel: "B2" as const, hebrewLevel: "מתקדם" as const, courseNameEnglish: "Urban planning and architecture", courseNameGerman: "Stadtplanung und Architektur", courseNameHebrew: "תכנון עירוני ואדריכלות", lessonCompleted: 0 }, 
    
      // C1
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "International relations", courseNameGerman: "Internationale Beziehungen", courseNameHebrew: "יחסים בינלאומיים", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Advanced literary analysis", courseNameGerman: "Fortgeschrittene literarische Analyse", courseNameHebrew: "ניתוח ספרותי מתקדם", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Philosophy and critical thinking", courseNameGerman: "Philosophie und kritisches Denken", courseNameHebrew: "פילוסופיה וחשיבה ביקורתית", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Advanced science topics (genetics, astronomy)", courseNameGerman: "Fortgeschrittene Wissenschaftsthemen (Genetik, Astronomie)", courseNameHebrew: "נושאים מדעיים מתקדמים (גנטיקה, אסטרונומיה)", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Advanced environmental studies", courseNameGerman: "Fortgeschrittene Umweltstudien", courseNameHebrew: "לימודי סביבה מתקדמים", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Journalism and reporting", courseNameGerman: "Journalismus und Berichterstattung", courseNameHebrew: "עיתונאות ודיווח", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Social justice", courseNameGerman: "Soziale Gerechtigkeit", courseNameHebrew: "צדק חברתי", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Politics and policies", courseNameGerman: "Politik und Richtlinien", courseNameHebrew: "פוליטיקה ומדיניות", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Historical conflicts and resolutions", courseNameGerman: "Historische Konflikte und Lösungen", courseNameHebrew: "קונפליקטים והסדרים היסטוריים", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Advanced art history", courseNameGerman: "Fortgeschrittene Kunstgeschichte", courseNameHebrew: "היסטוריה של האמנות המתקדמת", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Theater and performing arts", courseNameGerman: "Theater und darstellende Künste", courseNameHebrew: "תיאטרון ואמנויות הבמה", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Cultural anthropology", courseNameGerman: "Kulturelle Anthropologie", courseNameHebrew: "אנתרופולוגיה תרבותית", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Ethics in technology", courseNameGerman: "Ethik in der Technologie", courseNameHebrew: "אתיקה בטכנולוגיה", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Psychology and mental health", courseNameGerman: "Psychologie und psychische Gesundheit", courseNameHebrew: "פסיכולוגיה ובריאות הנפש", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Advanced business and economics", courseNameGerman: "Fortgeschrittenes Geschäft und Wirtschaft", courseNameHebrew: "עסקים וכלכלה מתקדמים", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Cryptocurrency and blockchain", courseNameGerman: "Kryptowährung und Blockchain", courseNameHebrew: "מטבעות קריפטוגרפיים ובלוקצ'יין", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Advanced debates", courseNameGerman: "Fortgeschrittene Debatten", courseNameHebrew: "דיונים מתקדמים", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Human rights issues", courseNameGerman: "Menschenrechtsfragen", courseNameHebrew: "סוגיות זכויות אדם", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Advanced language nuances", courseNameGerman: "Fortgeschrittene Sprachnuancen", courseNameHebrew: "ניואנסים בשפה מתקדמת", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Satire and humor in culture", courseNameGerman: "Satire und Humor in der Kultur", courseNameHebrew: "סטירה והומור בתרבות", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Advanced education policies", courseNameGerman: "Fortgeschrittene Bildungspolitik", courseNameHebrew: "מדיניות חינוך מתקדמת", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Space exploration", courseNameGerman: "Weltraumforschung", courseNameHebrew: "חקר החלל", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Technological ethics", courseNameGerman: "Technologische Ethik", courseNameHebrew: "אתיקה טכנולוגית", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Advanced social media strategies", courseNameGerman: "Fortgeschrittene Strategien für soziale Medien", courseNameHebrew: "אסטרטגיות מתקדמות במדיה חברתית", lessonCompleted: 0 }, 
      { englishLevel: "C1" as const, hebrewLevel: "מתקדם מאוד" as const, courseNameEnglish: "Advanced networking", courseNameGerman: "Fortgeschrittene Netzwerke", courseNameHebrew: "רישות מתקדם", lessonCompleted: 0 }, 
    
  
    // C2
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Advanced geopolitics", courseNameGerman: "Fortgeschrittene Geopolitik", courseNameHebrew: "גאופוליטיקה מתקדמת", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Abstract art and symbolism", courseNameGerman: "Abstrakte Kunst und Symbolik", courseNameHebrew: "אמנות מופשטת וסמליות", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Quantum physics basics", courseNameGerman: "Grundlagen der Quantenphysik", courseNameHebrew: "יסודות הפיזיקה הקוונטית", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Philosophy of mind", courseNameGerman: "Philosophie des Geistes", courseNameHebrew: "פילוסופיית הנפש", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Neuroscience", courseNameGerman: "Neurowissenschaft", courseNameHebrew: "מדעי המוח", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Global economic policies", courseNameGerman: "Globale Wirtschaftspolitik", courseNameHebrew: "מדיניות כלכלית גלובלית", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Advanced literary critique", courseNameGerman: "Fortgeschrittene Literaturkritik", courseNameHebrew: "ביקורת ספרותית מתקדמת", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Artificial intelligence ethics", courseNameGerman: "Ethik der künstlichen Intelligenz", courseNameHebrew: "אתיקה של בינה מלאכותית", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Linguistic studies and etymology", courseNameGerman: "Linguistische Studien und Etymologie", courseNameHebrew: "לימודי בלשנות ואטימולוגיה", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Advanced environmental law", courseNameGerman: "Fortgeschrittenes Umweltrecht", courseNameHebrew: "משפט סביבתי מתקדם", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Post-modern literature", courseNameGerman: "Postmoderne Literatur", courseNameHebrew: "ספרות פוסט-מודרנית", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "International diplomacy", courseNameGerman: "Internationale Diplomatie", courseNameHebrew: "דיפלומטיה בינלאומית", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "History of philosophy", courseNameGerman: "Geschichte der Philosophie", courseNameHebrew: "היסטוריה של פילוסופיה", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Avant-garde music and culture", courseNameGerman: "Avantgarde-Musik und Kultur", courseNameHebrew: "מוזיקה ותרבות אוונגרדית", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Deep learning and AI", courseNameGerman: "Deep Learning und KI", courseNameHebrew: "למידה עמוקה ובינה מלאכותית", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Global health crises", courseNameGerman: "Globale Gesundheitskrisen", courseNameHebrew: "משברים בריאותיים גלובליים", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Socio-political satire", courseNameGerman: "Soziopolitische Satire", courseNameHebrew: "סטירה חברתית-פוליטית", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Advanced film analysis", courseNameGerman: "Fortgeschrittene Filmanalyse", courseNameHebrew: "ניתוח קולנוע מתקדם", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Advanced cultural studies", courseNameGerman: "Fortgeschrittene Kulturwissenschaften", courseNameHebrew: "לימודי תרבות מתקדמים", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Advanced psychology topics (cognitive biases)", courseNameGerman: "Fortgeschrittene Psychologiethemen (kognitive Verzerrungen)", courseNameHebrew: "נושאים מתקדמים בפסיכולוגיה (הטיות קוגניטיביות)", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Advanced persuasive techniques", courseNameGerman: "Fortgeschrittene Überzeugungstechniken", courseNameHebrew: "טכניקות שכנוע מתקדמות", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Sustainability in design", courseNameGerman: "Nachhaltigkeit im Design", courseNameHebrew: "קיימות בעיצוב", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Ethical dilemmas in modern society", courseNameGerman: "Ethische Dilemmata in der modernen Gesellschaft", courseNameHebrew: "דילמות אתיות בחברה המודרנית", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Cross-cultural communication", courseNameGerman: "Interkulturelle Kommunikation", courseNameHebrew: "תקשורת בין-תרבותית", lessonCompleted: 0 }, 
    { englishLevel: "C2" as const, hebrewLevel: "שפת אם" as const, courseNameEnglish: "Advanced storytelling", courseNameGerman: "Fortgeschrittenes Geschichtenerzählen", courseNameHebrew: "סיפור סיפורים מתקדם", lessonCompleted: 0 }, 
  ];

  let index = 0;
  const courseData = courses.map((course) => ({
    ...course,
    userId,
    courseId: courseIds[index++]?.uuid, 
  }));
  
  await db.insert(CourseNames).values(courseData).returning({ id: CourseNames.courseId });
};