import { Words } from "../../drizzle/schema";
import { db } from "../../drizzle/db";
import { Word } from "../type/seedersType";
import { v4 as uuidv4 } from "uuid";

export const wordSeeder = async (userId: string, courseIds: Array<{ index: number; uuid: string; courseName: string }>) => {

  console.log("Seeding database...");

  const words: Word[] = [
    // Colors
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "es tut mir leid", hebrewWord: "סליחה", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "entschuldigung", hebrewWord: "סליחה", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "rot", hebrewWord: "אדום", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "blau", hebrewWord: "כחול", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "grün", hebrewWord: "ירוק", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "gelb", hebrewWord: "צהוב", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "schwarz", hebrewWord: "שחור" , knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "weiß", hebrewWord: "לבן", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "grau", hebrewWord: "אפור", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "braun", hebrewWord: "חום" , knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "rosa", hebrewWord: "ורוד", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "orange", hebrewWord: "כתום", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "lila", hebrewWord: "סגול", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "hellblau", hebrewWord: "תכלת", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "dunkelgrün", hebrewWord: "ירוק כהה", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "beige", hebrewWord: "בז'", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "violett", hebrewWord: "ארגמן", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "gold", hebrewWord: "זהב", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "silber", hebrewWord: "כסף", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "zinnober", hebrewWord: "אדמדם", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "kupfer", hebrewWord: "נחושת", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "karmin", hebrewWord: "קרמין", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "oliv", hebrewWord: "זית", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "türkis", hebrewWord: "טורקיז", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "indigo", hebrewWord: "אינדיגו", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "karmesinrot", hebrewWord: "אדום קרמזין", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "smaragdgrün", hebrewWord: "ירוק אזמרגד", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "bernstein", hebrewWord: "ענבר", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "mahagoni", hebrewWord: "מהגוני", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "schneeweiß", hebrewWord: "לבן שלג", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "kohlrabenschwarz", hebrewWord: "שחור כזפת", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "kakao", hebrewWord: "קקאו", knowledge: "X" },

    // Numbers
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "eins", hebrewWord: "אחד", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "zwei", hebrewWord: "שתיים", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "drei", hebrewWord: "שלוש", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "vier", hebrewWord: "ארבע", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "fünf", hebrewWord: "חמש", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "sechs", hebrewWord: "שש", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "sieben", hebrewWord: "שבע", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "acht", hebrewWord: "שמונה", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "neun", hebrewWord: "תשע", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "zehn", hebrewWord: "עשר", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "elf", hebrewWord: "אחד עשרה", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "zwölf", hebrewWord: "שתים עשרה", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "dreizehn", hebrewWord: "שלוש עשרה", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "vierzehn", hebrewWord: "ארבע עשרה", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "fünfzehn", hebrewWord: "חמש עשרה", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "sechzehn", hebrewWord: "שש עשרה", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "siebzehn", hebrewWord: "שבע עשרה", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "achtzehn", hebrewWord: "שמונה עשרה", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "neunzehn", hebrewWord: "תשע עשרה", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "zwanzig", hebrewWord: "עשרים", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "einundzwanzig", hebrewWord: "עשרים ואחד", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "zweiundzwanzig", hebrewWord: "עשרים ושתיים", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "dreiundzwanzig", hebrewWord: "עשרים ושלוש", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "vierundzwanzig", hebrewWord: "עשרים וארבע", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "fünfundzwanzig", hebrewWord: "עשרים וחמש", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "sechsundzwanzig", hebrewWord: "עשרים ושש", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "siebenundzwanzig", hebrewWord: "עשרים ושבע", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "achtundzwanzig", hebrewWord: "עשרים ושמונה", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "neunundzwanzig", hebrewWord: "עשרים ותשע", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "dreißig", hebrewWord: "שלושים", knowledge: "?" },

    // Fammily Members
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Vater", hebrewWord: "אבא", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Mutter", hebrewWord: "אמא", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Bruder", hebrewWord: "אח", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Schwester", hebrewWord: "אחות", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Opa", hebrewWord: "סבא", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Oma", hebrewWord: "סבתא", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Onkel", hebrewWord: "דוד", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Tante", hebrewWord: "דודה", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Cousin", hebrewWord: "בן דוד", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Cousine", hebrewWord: "בת דוד", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Neffe", hebrewWord: "אחיין", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Nichte", hebrewWord: "אחיינית", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Enkel", hebrewWord: "נכד", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Enkelin", hebrewWord: "נכדה", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Schwager", hebrewWord: "גיס", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Schwägerin", hebrewWord: "גיסה", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Schwiegervater", hebrewWord: "חותן", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Schwiegermutter", hebrewWord: "חמות", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Schwiegersohn", hebrewWord: "חתן", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Schwiegertochter", hebrewWord: "כלה", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Ehemann", hebrewWord: "בעל", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Ehefrau", hebrewWord: "אשה", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Sohn", hebrewWord: "בן", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Tochter", hebrewWord: "בת", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Großvater", hebrewWord: "סבא רבא", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Großmutter", hebrewWord: "סבתא רבתא", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Urenkel", hebrewWord: "נין", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Urenkelin", hebrewWord: "נינה", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Halbbruder", hebrewWord: "אח למחצה", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Halbschwester", hebrewWord: "אחות למחצה", knowledge: "V" },

    // Days of the Week
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Montag", hebrewWord: "יום שני", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Dienstag", hebrewWord: "יום שלישי", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Mittwoch", hebrewWord: "יום רביעי", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Donnerstag", hebrewWord: "יום חמישי", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Freitag", hebrewWord: "יום שישי", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Samstag", hebrewWord: "שבת", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Sonntag", hebrewWord: "יום ראשון", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Wochenbeginn", hebrewWord: "תחילת שבוע", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Wochenende", hebrewWord: "סוף שבוע", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Montagmorgen", hebrewWord: "בוקר יום שני", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Dienstagabend", hebrewWord: "ערב יום שלישי", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Mittwochnachmittag", hebrewWord: "אחר הצהריים של יום רביעי", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Donnerstagnacht", hebrewWord: "לילה של יום חמישי", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Freitagmorgen", hebrewWord: "בוקר יום שישי", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Samstagabend", hebrewWord: "ערב שבת", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Sonntagvormittag", hebrewWord: "לפני הצהריים של יום ראשון", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Erster Tag", hebrewWord: "יום ראשון", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Letzter Tag", hebrewWord: "יום אחרון", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Arbeitstag", hebrewWord: "יום עבודה", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Ruhetag", hebrewWord: "יום מנוחה", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Gestern", hebrewWord: "אתמול", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Heute", hebrewWord: "היום", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Morgen", hebrewWord: "מחר", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Früher", hebrewWord: "לפני כן", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Später", hebrewWord: "אחרי כן", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Nächste Woche", hebrewWord: "שבוע הבא", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Letzte Woche", hebrewWord: "שבוע שעבר", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Zukunftstag", hebrewWord: "יום בעתיד", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Vergangener Tag", hebrewWord: "יום שעבר", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Freie Tage", hebrewWord: "ימי חופשה", knowledge: "X" },

    // Months
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "Januar", hebrewWord: "ינואר", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "Februar", hebrewWord: "פברואר", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "März", hebrewWord: "מרץ", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "April", hebrewWord: "אפריל", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "Mai", hebrewWord: "מאי", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "Juni", hebrewWord: "יוני", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "Juli", hebrewWord: "יולי", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "August", hebrewWord: "אוגוסט", knowledge: "?" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "September", hebrewWord: "ספטמבר", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "Oktober", hebrewWord: "אוקטובר", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "November", hebrewWord: "נובמבר", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "Dezember", hebrewWord: "דצמבר", knowledge: "X" },

    // Greetings
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Wie heißen Sie", hebrewWord: "איך קוראים לך", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "ich", hebrewWord: "אני", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "heiße", hebrewWord: "קוראים", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Hallo", hebrewWord: "שלום", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Servus", hebrewWord: "שלום", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Guten Morgen", hebrewWord: "בוקר טוב", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Guten Tag", hebrewWord: "צהריים טובים", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Guten Abend", hebrewWord: "ערב טוב", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Gute Nacht", hebrewWord: "לילה טוב", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "hi", hebrewWord: "היי", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Wie geht's?", hebrewWord: "מה שלומך", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Auf Wiedersehen", hebrewWord: "להתראות", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Tschüss", hebrewWord: "ביי", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Bis bald", hebrewWord: "נתראה בקרוב", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Herzlich willkommen", hebrewWord: "ברוך הבא", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Schönen Tag noch", hebrewWord: "שיהיה לך יום נעים", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Viel Glück", hebrewWord: "בהצלחה", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Alles Gute", hebrewWord: "כל טוב", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Guten Appetit", hebrewWord: "בתיאבון", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Schlaf gut", hebrewWord: "שינה טובה", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Grüß Gott", hebrewWord: "ברך את ה'", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Moin", hebrewWord: "שלום (צפון גרמניה)", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Servus", hebrewWord: "שלום (דרום גרמניה)", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Prost", hebrewWord: "לחיים", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Schönen Abend noch", hebrewWord: "שיהיה לך ערב נעים", knowledge: "V" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Ich wünsche dir einen schönen Tag", hebrewWord: "אני מאחל לך יום נעים", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Bis später", hebrewWord: "נתראה מאוחר יותר", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Bis morgen", hebrewWord: "נתראה מחר", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Bis nächste Woche", hebrewWord: "נתראה בשבוע הבא", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Schön dich zu sehen", hebrewWord: "נחמד לראות אותך", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Es freut mich, dich zu treffen", hebrewWord: "שמחתי לפגוש אותך", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Ich freue mich, Sie zu sehen", hebrewWord: "שמחתי לראות אותך (רשמי)", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Ich hoffe, es geht dir gut", hebrewWord: "אני מקווה שאתה בסדר", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Herzlichen Glückwunsch", hebrewWord: "מזל טוב", knowledge: "X" },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Frohes neues Jahr", hebrewWord: "שנה טובה", knowledge: "X" },

    // Weather
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist sonnig", hebrewWord: "יש שמש", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist wolkig", hebrewWord: "מעונן", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es regnet", hebrewWord: "יורד גשם", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es schneit", hebrewWord: "יורד שלג", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist windig", hebrewWord: "יש רוח", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist heiß", hebrewWord: "חם", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist kalt", hebrewWord: "קר", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist neblig", hebrewWord: "יש ערפל", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist stürmisch", hebrewWord: "סוער", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist trocken", hebrewWord: "יבש", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist nass", hebrewWord: "רטוב", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt Gewitter", hebrewWord: "יש סופת רעמים", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist warm", hebrewWord: "חמים", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist kühl", hebrewWord: "קריר", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist wechselhaft", hebrewWord: "משתנה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt einen Regenbogen", hebrewWord: "יש קשת בענן", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es hagelt", hebrewWord: "יורד ברד", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Der Himmel ist klar", hebrewWord: "השמיים בהירים", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Der Himmel ist bedeckt", hebrewWord: "השמיים מכוסים", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt eine Hitzewelle", hebrewWord: "יש גל חום", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt eine Kältewelle", hebrewWord: "יש גל קור", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt starken Wind", hebrewWord: "יש רוח חזקה", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt dichten Nebel", hebrewWord: "יש ערפל כבד", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist bewölkt", hebrewWord: "מעונן חלקית", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist schwül", hebrewWord: "לח מאוד", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist angenehm", hebrewWord: "נעים", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt einen starken Sturm", hebrewWord: "יש סופה חזקה", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt leichtes Nieseln", hebrewWord: "יש טפטוף קל", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es regnet in Strömen", hebrewWord: "יורד גשם כבד", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt einen Schneesturm", hebrewWord: "יש סופת שלגים", knowledge: "?" },

// Basic Clothing
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "das Hemd", hebrewWord: "חולצה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Hose", hebrewWord: "מכנסיים", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "das Kleid", hebrewWord: "שמלה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Jacke", hebrewWord: "מעיל", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Schuhe", hebrewWord: "נעליים", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Socken", hebrewWord: "גרביים", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Mütze", hebrewWord: "כובע צמר", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "der Hut", hebrewWord: "כובע", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Handschuhe", hebrewWord: "כפפות", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "der Schal", hebrewWord: "צעיף", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Bluse", hebrewWord: "חולצת נשים", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Unterwäsche", hebrewWord: "תחתונים", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "das T-Shirt", hebrewWord: "טי-שירט", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Jeans", hebrewWord: "ג'ינס", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Sandalen", hebrewWord: "סנדלים", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Stiefel", hebrewWord: "מגפיים", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Weste", hebrewWord: "אפוד", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "der Pullover", hebrewWord: "סוודר", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Krawatte", hebrewWord: "עניבה", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "das Kostüm", hebrewWord: "חליפה (נשים)", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "der Anzug", hebrewWord: "חליפה (גברים)", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Shorts", hebrewWord: "מכנסיים קצרים", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "der Mantel", hebrewWord: "מעיל ארוך", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Strümpfe", hebrewWord: "גרביים ארוכים", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "der Gürtel", hebrewWord: "חגורה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Regenjacke", hebrewWord: "מעיל גשם", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "das Nachthemd", hebrewWord: "כתונת לילה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Bademode", hebrewWord: "בגד ים", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Hausschuhe", hebrewWord: "נעלי בית", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Schürze", hebrewWord: "סינר", knowledge: "X" },
// Common Food Items
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "das Brot", hebrewWord: "לחם", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Butter", hebrewWord: "חמאה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Milch", hebrewWord: "חלב", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "das Ei", hebrewWord: "ביצה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Käse", hebrewWord: "גבינה", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Apfel", hebrewWord: "תפוח", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Banane", hebrewWord: "בננה", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Orange", hebrewWord: "תפוז", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Kartoffel", hebrewWord: "תפוח אדמה", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Tomate", hebrewWord: "עגבנייה", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Gurke", hebrewWord: "מלפפון", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Salat", hebrewWord: "סלט", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "das Fleisch", hebrewWord: "בשר", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Fisch", hebrewWord: "דג", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "das Hähnchen", hebrewWord: "עוף", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Reis", hebrewWord: "אורז", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Nudeln", hebrewWord: "אטריות", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "das Salz", hebrewWord: "מלח", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Zucker", hebrewWord: "סוכר", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Honig", hebrewWord: "דבש", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Marmelade", hebrewWord: "ריבה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Schokolade", hebrewWord: "שוקולד", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "das Wasser", hebrewWord: "מים", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Saft", hebrewWord: "מיץ", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "das Bier", hebrewWord: "בירה", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Wein", hebrewWord: "יין", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Kaffee", hebrewWord: "קפה", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Tee", hebrewWord: "תה", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Zwiebel", hebrewWord: "בצל", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Knoblauch", hebrewWord: "שום", knowledge: "V" },

// House Parts
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Wohnzimmer", hebrewWord: "סלון", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Schlafzimmer", hebrewWord: "חדר שינה", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Küche", hebrewWord: "מטבח", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Badezimmer", hebrewWord: "חדר אמבטיה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Esszimmer", hebrewWord: "חדר אוכל", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Kinderzimmer", hebrewWord: "חדר ילדים", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Keller", hebrewWord: "מרתף", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Dachboden", hebrewWord: "עליית גג", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Flur", hebrewWord: "מסדרון", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Tür", hebrewWord: "דלת", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Fenster", hebrewWord: "חלון", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Garten", hebrewWord: "גן", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Balkon", hebrewWord: "מרפסת", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Treppe", hebrewWord: "מדרגות", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Dach", hebrewWord: "גג", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Wand", hebrewWord: "קיר", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Boden", hebrewWord: "רצפה", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Decke", hebrewWord: "תקרה", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Garage", hebrewWord: "מוסך", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Hof", hebrewWord: "חצר", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Haustür", hebrewWord: "דלת כניסה", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Kamin", hebrewWord: "אח", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Veranda", hebrewWord: "מרפסת מקורה", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Waschküche", hebrewWord: "חדר כביסה", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Büro", hebrewWord: "משרד", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Terrasse", hebrewWord: "טרסה", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Gästezimmer", hebrewWord: "חדר אורחים", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Vorratskammer", hebrewWord: "מזווה", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Badezimmer", hebrewWord: "חדר שירותים", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Eingangshalle", hebrewWord: "אולם כניסה", knowledge: "V" },

// Animals
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Hund", hebrewWord: "כלב", knowledge: "V" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Katze", hebrewWord: "חתול", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "das Pferd", hebrewWord: "סוס", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Kuh", hebrewWord: "פרה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "das Schwein", hebrewWord: "חזיר", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "das Schaf", hebrewWord: "כבשה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Ziege", hebrewWord: "עז", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Hase", hebrewWord: "ארנב", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Fuchs", hebrewWord: "שועל", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Bär", hebrewWord: "דוב", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Löwe", hebrewWord: "אריה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Tiger", hebrewWord: "טיגריס", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Elefant", hebrewWord: "פיל", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Maus", hebrewWord: "עכבר", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Vogel", hebrewWord: "ציפור", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Fisch", hebrewWord: "דג", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Schlange", hebrewWord: "נחש", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Spinne", hebrewWord: "עכביש", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Affe", hebrewWord: "קוף", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "das Känguru", hebrewWord: "קנגורו", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Delfin", hebrewWord: "דולפין", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Wal", hebrewWord: "לוויתן", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Pinguin", hebrewWord: "פינגווין", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "das Krokodil", hebrewWord: "תנין", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Schmetterling", hebrewWord: "פרפר", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Ameise", hebrewWord: "נמלה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Biene", hebrewWord: "דבורה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Hahn", hebrewWord: "תרנגול", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Ente", hebrewWord: "ברווז", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Gans", hebrewWord: "אווז", knowledge: "X" },

// Basic Emotions
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "glücklich", hebrewWord: "שמח", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "traurig", hebrewWord: "עצוב", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "wütend", hebrewWord: "כועס", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "aufgeregt", hebrewWord: "נרגש", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "ängstlich", hebrewWord: "מפוחד", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "zufrieden", hebrewWord: "מרוצה", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "überrascht", hebrewWord: "מופתע", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "gelangweilt", hebrewWord: "משועמם", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "besorgt", hebrewWord: "מודאג", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "verliebt", hebrewWord: "מאוהב", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "neidisch", hebrewWord: "מקנא", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "dankbar", hebrewWord: "מודה", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "müde", hebrewWord: "עייף", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "verärgert", hebrewWord: "כועס", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "schüchtern", hebrewWord: "ביישן", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "stolz", hebrewWord: "גאה", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "verwirrt", hebrewWord: "מבולבל", knowledge: "?" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "einsam", hebrewWord: "בודד", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "frustriert", hebrewWord: "מתוסכל", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "hoffnungsvoll", hebrewWord: "מקווה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "erschöpft", hebrewWord: "מותש", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "verletzt", hebrewWord: "נפגע", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "eifersüchtig", hebrewWord: "קנאי", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "beschämt", hebrewWord: "מתבייש", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "entspannt", hebrewWord: "רגוע", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "unwohl", hebrewWord: "לא בנוח", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "aufmerksam", hebrewWord: "קשוב", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "vergnügt", hebrewWord: "מרוצה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "hoffnungslos", hebrewWord: "חסר תקווה", knowledge: "X" },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "erleichtert", hebrewWord: "מוקל", knowledge: "X" },

// A2
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "seasons", germanWord: "sommer", hebrewWord: "קיץ", knowledge: "X" },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "seasons", germanWord: "winter", hebrewWord: "חורף", knowledge: "X" },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "seasons", germanWord: "herbst", hebrewWord: "סתיו", knowledge: "X" },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "seasons", germanWord: "frühling", hebrewWord: "אביב", knowledge: "?" },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Apfel", hebrewWord: "תפוח", knowledge: "?" },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Brot", hebrewWord: "לחם", knowledge: "?" },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Milch", hebrewWord: "חלב", knowledge: "?" },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Eier", hebrewWord: "ביצים", knowledge: "X" },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Käse", hebrewWord: "גבינה", knowledge: "V" },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Butter", hebrewWord: "חמאה", knowledge: "V" },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Fleisch", hebrewWord: "בשר", knowledge: "V" },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Gemüse", hebrewWord: "ירקות", knowledge: "V" },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Obst", hebrewWord: "פירות", knowledge: "V" },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Wasser", hebrewWord: "מים", knowledge: "X" },

// B1
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Zeitung", hebrewWord: "עיתון", knowledge: "X" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Nachrichten", hebrewWord: "חדשות", knowledge: "X" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Reporter", hebrewWord: "כתב", knowledge: "X" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Interview", hebrewWord: "ראיון", knowledge: "X" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Artikel", hebrewWord: "מאמר", knowledge: "X" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Fernsehen", hebrewWord: "טלוויזיה", knowledge: "?" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Radio", hebrewWord: "רדיו", knowledge: "?" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Überschrift", hebrewWord: "כותרת", knowledge: "?" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Online-Medien", hebrewWord: "מדיה מקוונת", knowledge: "?" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Nachrichtensprecher", hebrewWord: "מגיש חדשות", knowledge: "?" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Baum", hebrewWord: "עץ", knowledge: "?" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Fluss", hebrewWord: "נהר", knowledge: "X" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Berg", hebrewWord: "הר", knowledge: "X" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Wald", hebrewWord: "יער", knowledge: "?" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "See", hebrewWord: "אגם", knowledge: "?" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Vogel", hebrewWord: "ציפור", knowledge: "?" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Löwe", hebrewWord: "אריה", knowledge: "?" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Fisch", hebrewWord: "דג", knowledge: "?" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Blume", hebrewWord: "פרח", knowledge: "?" },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Schmetterling", hebrewWord: "פרפר", knowledge: "?" },

// B2
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Freiwilliger", hebrewWord: "מתנדב", knowledge: "X" },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Spende", hebrewWord: "תרומה", knowledge: "X" },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Organisation", hebrewWord: "ארגון", knowledge: "X" },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Hilfsprojekt", hebrewWord: "פרויקט סיוע", knowledge: "?" },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Mitgefühl", hebrewWord: "אמפתיה", knowledge: "?" },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Fundraising", hebrewWord: "גיוס כספים", knowledge: "?" },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Gemeinschaft", hebrewWord: "קהילה", knowledge: "V" },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Ehrenamt", hebrewWord: "התנדבות", knowledge: "V" },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Wohltätigkeit", hebrewWord: "צדקה", knowledge: "V" },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Nächstenliebe", hebrewWord: "אהבת הזולת", knowledge: "X" },

// C1
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Menschenrechte", hebrewWord: "זכויות אדם", knowledge: "X" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Gerechtigkeit", hebrewWord: "צדק", knowledge: "X" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Freiheit", hebrewWord: "חירות", knowledge: "X" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Diskriminierung", hebrewWord: "אפליה", knowledge: "X" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Asyl", hebrewWord: "מקלט", knowledge: "X" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Gleichheit", hebrewWord: "שוויון", knowledge: "V" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Unterdrückung", hebrewWord: "דיכוי", knowledge: "V" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Kinderarbeit", hebrewWord: "עבודת ילדים", knowledge: "V" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Meinungsfreiheit", hebrewWord: "חופש הביטוי", knowledge: "V" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Toleranz", hebrewWord: "סובלנות", knowledge: "V" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Weltraum", hebrewWord: "חלל", knowledge: "V" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Rakete", hebrewWord: "רקטה", knowledge: "?" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Astronaut", hebrewWord: "אסטרונאוט", knowledge: "?" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Erde", hebrewWord: "כדור הארץ", knowledge: "?" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Mond", hebrewWord: "ירח", knowledge: "?" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Stern", hebrewWord: "כוכב", knowledge: "?" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Raumschiff", hebrewWord: "חללית", knowledge: "?" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Sonne", hebrewWord: "שמש", knowledge: "?" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Planeten", hebrewWord: "כוכבי לכת", knowledge: "?" },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Universum", hebrewWord: "יקום", knowledge: "?" },

// C2
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Gehirn", hebrewWord: "מוח", knowledge: "X" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Neuron", hebrewWord: "נוירון", knowledge: "X" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Synapse", hebrewWord: "סינפסה", knowledge: "X" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Nervensystem", hebrewWord: "מערכת העצבים", knowledge: "X" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Gedächtnis", hebrewWord: "זיכרון", knowledge: "X" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Emotion", hebrewWord: "רגש", knowledge: "X" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Hirnrinde", hebrewWord: "קליפת המוח", knowledge: "?" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Refle?", hebrewWord: "רפלקס", knowledge: "?" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Motorik", hebrewWord: "מוטוריקה", knowledge: "?" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Bewusstsein", hebrewWord: "מודעות", knowledge: "?" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Kognition", hebrewWord: "קוגניציה", knowledge: "?" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Dopamin", hebrewWord: "דופמין", knowledge: "?" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Hippocampus", hebrewWord: "היפוקמפוס", knowledge: "?" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Neurotransmitter", hebrewWord: "מוליך עצבי", knowledge: "?" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Plastizität", hebrewWord: "פלסטיות", knowledge: "?" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Stress", hebrewWord: "לחץ", knowledge: "V" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Sensorik", hebrewWord: "חישה", knowledge: "V" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Verarbeitung", hebrewWord: "עיבוד", knowledge: "V" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Impuls", hebrewWord: "דחף", knowledge: "V" },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Perzeption", hebrewWord: "תפיסה", knowledge: "V" },
];

const getUuidByCourseName = ( courseIds: Array<{ index: number; uuid: string; courseName: string }>, courseName: string ): string => {
  const resultItem = courseIds.find((item) => item.courseName.toLowerCase() === courseName.toLowerCase());
  if (!resultItem) {
    console.error(`Course name "${courseName}" not found in courseIds`);
    console.error("Available course names:", courseIds.map((item) => item.courseName));
    throw new Error(`Course name "${courseName}" not found in courseIds`);
  }
  return resultItem.uuid;
};

const wordData = words.map((word) => ({
  ...word,
  userId,
  wordId: uuidv4(),
  // courseId: getUuidByCourseName(courseIds, lesson.courseNameEnglish),
  courseId: getUuidByCourseName(courseIds, word.courseNameEnglish),

}));

await db.insert(Words).values(wordData).returning({ id: Words.courseId });
};