import { Words } from "../../drizzle/schema";
import { db } from "../../drizzle/db";
import { Word } from "../type/seedersType";

export const wordSeeder = async (userId: string, courseIds: Array<{ index: number; uuid: string; courseName: string }>) => {

  console.log("Seeding database...");

  const words: Word[] = [
    // Colors
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "es tut mir leid", hebrewWord: "סליחה", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "entschuldigung", hebrewWord: "סליחה", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "rot", hebrewWord: "אדום", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "blau", hebrewWord: "כחול", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "grün", hebrewWord: "ירוק", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "gelb", hebrewWord: "צהוב", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "schwarz", hebrewWord: "שחור" , knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "weiß", hebrewWord: "לבן", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "grau", hebrewWord: "אפור", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "braun", hebrewWord: "חום" , knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "rosa", hebrewWord: "ורוד", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "orange", hebrewWord: "כתום", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "lila", hebrewWord: "סגול", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "hellblau", hebrewWord: "תכלת", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "dunkelgrün", hebrewWord: "ירוק כהה", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "beige", hebrewWord: "בז'", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "violett", hebrewWord: "ארגמן", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "gold", hebrewWord: "זהב", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "silber", hebrewWord: "כסף", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "zinnober", hebrewWord: "אדמדם", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "kupfer", hebrewWord: "נחושת", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "karmin", hebrewWord: "קרמין", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "oliv", hebrewWord: "זית", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "türkis", hebrewWord: "טורקיז", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "indigo", hebrewWord: "אינדיגו", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "karmesinrot", hebrewWord: "אדום קרמזין", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "smaragdgrün", hebrewWord: "ירוק אזמרגד", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "bernstein", hebrewWord: "ענבר", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "mahagoni", hebrewWord: "מהגוני", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "schneeweiß", hebrewWord: "לבן שלג", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "kohlrabenschwarz", hebrewWord: "שחור כזפת", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Colors", germanWord: "kakao", hebrewWord: "קקאו", knowlage: "X" , userId },

    // Numbers
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "eins", hebrewWord: "אחד", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "zwei", hebrewWord: "שתיים", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "drei", hebrewWord: "שלוש", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "vier", hebrewWord: "ארבע", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "fünf", hebrewWord: "חמש", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "sechs", hebrewWord: "שש", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "sieben", hebrewWord: "שבע", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "acht", hebrewWord: "שמונה", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "neun", hebrewWord: "תשע", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "zehn", hebrewWord: "עשר", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "elf", hebrewWord: "אחד עשרה", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "zwölf", hebrewWord: "שתים עשרה", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "dreizehn", hebrewWord: "שלוש עשרה", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "vierzehn", hebrewWord: "ארבע עשרה", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "fünfzehn", hebrewWord: "חמש עשרה", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "sechzehn", hebrewWord: "שש עשרה", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "siebzehn", hebrewWord: "שבע עשרה", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "achtzehn", hebrewWord: "שמונה עשרה", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "neunzehn", hebrewWord: "תשע עשרה", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "zwanzig", hebrewWord: "עשרים", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "einundzwanzig", hebrewWord: "עשרים ואחד", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "zweiundzwanzig", hebrewWord: "עשרים ושתיים", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "dreiundzwanzig", hebrewWord: "עשרים ושלוש", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "vierundzwanzig", hebrewWord: "עשרים וארבע", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "fünfundzwanzig", hebrewWord: "עשרים וחמש", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "sechsundzwanzig", hebrewWord: "עשרים ושש", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "siebenundzwanzig", hebrewWord: "עשרים ושבע", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "achtundzwanzig", hebrewWord: "עשרים ושמונה", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "neunundzwanzig", hebrewWord: "עשרים ותשע", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Numbers", germanWord: "dreißig", hebrewWord: "שלושים", knowlage: "?" , userId },

    // Fammily Members
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Vater", hebrewWord: "אבא", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Mutter", hebrewWord: "אמא", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Bruder", hebrewWord: "אח", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Schwester", hebrewWord: "אחות", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Opa", hebrewWord: "סבא", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Oma", hebrewWord: "סבתא", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Onkel", hebrewWord: "דוד", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Tante", hebrewWord: "דודה", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Cousin", hebrewWord: "בן דוד", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Cousine", hebrewWord: "בת דוד", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Neffe", hebrewWord: "אחיין", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Nichte", hebrewWord: "אחיינית", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Enkel", hebrewWord: "נכד", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Enkelin", hebrewWord: "נכדה", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Schwager", hebrewWord: "גיס", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Schwägerin", hebrewWord: "גיסה", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Schwiegervater", hebrewWord: "חותן", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Schwiegermutter", hebrewWord: "חמות", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Schwiegersohn", hebrewWord: "חתן", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Schwiegertochter", hebrewWord: "כלה", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Ehemann", hebrewWord: "בעל", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Ehefrau", hebrewWord: "אשה", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Sohn", hebrewWord: "בן", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Tochter", hebrewWord: "בת", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Großvater", hebrewWord: "סבא רבא", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Großmutter", hebrewWord: "סבתא רבתא", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Urenkel", hebrewWord: "נין", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Urenkelin", hebrewWord: "נינה", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Halbbruder", hebrewWord: "אח למחצה", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Family members", germanWord: "Halbschwester", hebrewWord: "אחות למחצה", knowlage: "V" , userId },

    // Days of the Week
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Montag", hebrewWord: "יום שני", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Dienstag", hebrewWord: "יום שלישי", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Mittwoch", hebrewWord: "יום רביעי", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Donnerstag", hebrewWord: "יום חמישי", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Freitag", hebrewWord: "יום שישי", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Samstag", hebrewWord: "שבת", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Sonntag", hebrewWord: "יום ראשון", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Wochenbeginn", hebrewWord: "תחילת שבוע", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Wochenende", hebrewWord: "סוף שבוע", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Montagmorgen", hebrewWord: "בוקר יום שני", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Dienstagabend", hebrewWord: "ערב יום שלישי", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Mittwochnachmittag", hebrewWord: "אחר הצהריים של יום רביעי", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Donnerstagnacht", hebrewWord: "לילה של יום חמישי", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Freitagmorgen", hebrewWord: "בוקר יום שישי", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Samstagabend", hebrewWord: "ערב שבת", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Sonntagvormittag", hebrewWord: "לפני הצהריים של יום ראשון", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Erster Tag", hebrewWord: "יום ראשון", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Letzter Tag", hebrewWord: "יום אחרון", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Arbeitstag", hebrewWord: "יום עבודה", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Ruhetag", hebrewWord: "יום מנוחה", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Gestern", hebrewWord: "אתמול", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Heute", hebrewWord: "היום", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Morgen", hebrewWord: "מחר", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Früher", hebrewWord: "לפני כן", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Später", hebrewWord: "אחרי כן", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Nächste Woche", hebrewWord: "שבוע הבא", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Letzte Woche", hebrewWord: "שבוע שעבר", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Zukunftstag", hebrewWord: "יום בעתיד", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Vergangener Tag", hebrewWord: "יום שעבר", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Days of the Week", germanWord: "Freie Tage", hebrewWord: "ימי חופשה", knowlage: "X" , userId },

    // Months
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "Januar", hebrewWord: "ינואר", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "Februar", hebrewWord: "פברואר", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "März", hebrewWord: "מרץ", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "April", hebrewWord: "אפריל", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "Mai", hebrewWord: "מאי", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "Juni", hebrewWord: "יוני", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "Juli", hebrewWord: "יולי", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "August", hebrewWord: "אוגוסט", knowlage: "?" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "September", hebrewWord: "ספטמבר", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "Oktober", hebrewWord: "אוקטובר", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "November", hebrewWord: "נובמבר", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Months", germanWord: "Dezember", hebrewWord: "דצמבר", knowlage: "X" , userId },

    // Greetings
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Wie heißen Sie", hebrewWord: "איך קוראים לך", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "ich", hebrewWord: "אני", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "heiße", hebrewWord: "קוראים", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Hallo", hebrewWord: "שלום", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Servus", hebrewWord: "שלום", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Guten Morgen", hebrewWord: "בוקר טוב", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Guten Tag", hebrewWord: "צהריים טובים", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Guten Abend", hebrewWord: "ערב טוב", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Gute Nacht", hebrewWord: "לילה טוב", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "hi", hebrewWord: "היי", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Wie geht's?", hebrewWord: "מה שלומך", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Auf Wiedersehen", hebrewWord: "להתראות", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Tschüss", hebrewWord: "ביי", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Bis bald", hebrewWord: "נתראה בקרוב", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Herzlich willkommen", hebrewWord: "ברוך הבא", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Schönen Tag noch", hebrewWord: "שיהיה לך יום נעים", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Viel Glück", hebrewWord: "בהצלחה", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Alles Gute", hebrewWord: "כל טוב", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Guten Appetit", hebrewWord: "בתיאבון", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Schlaf gut", hebrewWord: "שינה טובה", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Grüß Gott", hebrewWord: "ברך את ה'", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Moin", hebrewWord: "שלום (צפון גרמניה)", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Servus", hebrewWord: "שלום (דרום גרמניה)", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Prost", hebrewWord: "לחיים", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Schönen Abend noch", hebrewWord: "שיהיה לך ערב נעים", knowlage: "V" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Ich wünsche dir einen schönen Tag", hebrewWord: "אני מאחל לך יום נעים", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Bis später", hebrewWord: "נתראה מאוחר יותר", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Bis morgen", hebrewWord: "נתראה מחר", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Bis nächste Woche", hebrewWord: "נתראה בשבוע הבא", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Schön dich zu sehen", hebrewWord: "נחמד לראות אותך", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Es freut mich, dich zu treffen", hebrewWord: "שמחתי לפגוש אותך", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Ich freue mich, Sie zu sehen", hebrewWord: "שמחתי לראות אותך (רשמי)", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Ich hoffe, es geht dir gut", hebrewWord: "אני מקווה שאתה בסדר", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Herzlichen Glückwunsch", hebrewWord: "מזל טוב", knowlage: "X" , userId },
    { hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Greetings", germanWord: "Frohes neues Jahr", hebrewWord: "שנה טובה", knowlage: "X" , userId },

    // Weather
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist sonnig", hebrewWord: "יש שמש", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist wolkig", hebrewWord: "מעונן", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es regnet", hebrewWord: "יורד גשם", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es schneit", hebrewWord: "יורד שלג", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist windig", hebrewWord: "יש רוח", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist heiß", hebrewWord: "חם", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist kalt", hebrewWord: "קר", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist neblig", hebrewWord: "יש ערפל", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist stürmisch", hebrewWord: "סוער", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist trocken", hebrewWord: "יבש", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist nass", hebrewWord: "רטוב", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt Gewitter", hebrewWord: "יש סופת רעמים", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist warm", hebrewWord: "חמים", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist kühl", hebrewWord: "קריר", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist wechselhaft", hebrewWord: "משתנה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt einen Regenbogen", hebrewWord: "יש קשת בענן", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es hagelt", hebrewWord: "יורד ברד", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Der Himmel ist klar", hebrewWord: "השמיים בהירים", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Der Himmel ist bedeckt", hebrewWord: "השמיים מכוסים", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt eine Hitzewelle", hebrewWord: "יש גל חום", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt eine Kältewelle", hebrewWord: "יש גל קור", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt starken Wind", hebrewWord: "יש רוח חזקה", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt dichten Nebel", hebrewWord: "יש ערפל כבד", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist bewölkt", hebrewWord: "מעונן חלקית", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist schwül", hebrewWord: "לח מאוד", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es ist angenehm", hebrewWord: "נעים", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt einen starken Sturm", hebrewWord: "יש סופה חזקה", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt leichtes Nieseln", hebrewWord: "יש טפטוף קל", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es regnet in Strömen", hebrewWord: "יורד גשם כבד", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Weather", germanWord: "Es gibt einen Schneesturm", hebrewWord: "יש סופת שלגים", knowlage: "?" , userId },

// Basic Clothing
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "das Hemd", hebrewWord: "חולצה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Hose", hebrewWord: "מכנסיים", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "das Kleid", hebrewWord: "שמלה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Jacke", hebrewWord: "מעיל", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Schuhe", hebrewWord: "נעליים", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Socken", hebrewWord: "גרביים", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Mütze", hebrewWord: "כובע צמר", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "der Hut", hebrewWord: "כובע", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Handschuhe", hebrewWord: "כפפות", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "der Schal", hebrewWord: "צעיף", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Bluse", hebrewWord: "חולצת נשים", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Unterwäsche", hebrewWord: "תחתונים", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "das T-Shirt", hebrewWord: "טי-שירט", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Jeans", hebrewWord: "ג'ינס", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Sandalen", hebrewWord: "סנדלים", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Stiefel", hebrewWord: "מגפיים", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Weste", hebrewWord: "אפוד", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "der Pullover", hebrewWord: "סוודר", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Krawatte", hebrewWord: "עניבה", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "das Kostüm", hebrewWord: "חליפה (נשים)", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "der Anzug", hebrewWord: "חליפה (גברים)", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Shorts", hebrewWord: "מכנסיים קצרים", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "der Mantel", hebrewWord: "מעיל ארוך", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Strümpfe", hebrewWord: "גרביים ארוכים", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "der Gürtel", hebrewWord: "חגורה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Regenjacke", hebrewWord: "מעיל גשם", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "das Nachthemd", hebrewWord: "כתונת לילה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Bademode", hebrewWord: "בגד ים", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Hausschuhe", hebrewWord: "נעלי בית", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Clothing", germanWord: "die Schürze", hebrewWord: "סינר", knowlage: "X" , userId },
// Common Food Items
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "das Brot", hebrewWord: "לחם", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Butter", hebrewWord: "חמאה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Milch", hebrewWord: "חלב", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "das Ei", hebrewWord: "ביצה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Käse", hebrewWord: "גבינה", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Apfel", hebrewWord: "תפוח", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Banane", hebrewWord: "בננה", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Orange", hebrewWord: "תפוז", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Kartoffel", hebrewWord: "תפוח אדמה", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Tomate", hebrewWord: "עגבנייה", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Gurke", hebrewWord: "מלפפון", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Salat", hebrewWord: "סלט", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "das Fleisch", hebrewWord: "בשר", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Fisch", hebrewWord: "דג", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "das Hähnchen", hebrewWord: "עוף", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Reis", hebrewWord: "אורז", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Nudeln", hebrewWord: "אטריות", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "das Salz", hebrewWord: "מלח", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Zucker", hebrewWord: "סוכר", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Honig", hebrewWord: "דבש", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Marmelade", hebrewWord: "ריבה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Schokolade", hebrewWord: "שוקולד", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "das Wasser", hebrewWord: "מים", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Saft", hebrewWord: "מיץ", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "das Bier", hebrewWord: "בירה", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Wein", hebrewWord: "יין", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Kaffee", hebrewWord: "קפה", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Tee", hebrewWord: "תה", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "die Zwiebel", hebrewWord: "בצל", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Common Food Items", germanWord: "der Knoblauch", hebrewWord: "שום", knowlage: "V" , userId },

// House Parts
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Wohnzimmer", hebrewWord: "סלון", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Schlafzimmer", hebrewWord: "חדר שינה", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Küche", hebrewWord: "מטבח", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Badezimmer", hebrewWord: "חדר אמבטיה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Esszimmer", hebrewWord: "חדר אוכל", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Kinderzimmer", hebrewWord: "חדר ילדים", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Keller", hebrewWord: "מרתף", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Dachboden", hebrewWord: "עליית גג", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Flur", hebrewWord: "מסדרון", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Tür", hebrewWord: "דלת", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Fenster", hebrewWord: "חלון", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Garten", hebrewWord: "גן", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Balkon", hebrewWord: "מרפסת", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Treppe", hebrewWord: "מדרגות", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Dach", hebrewWord: "גג", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Wand", hebrewWord: "קיר", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Boden", hebrewWord: "רצפה", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Decke", hebrewWord: "תקרה", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Garage", hebrewWord: "מוסך", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Hof", hebrewWord: "חצר", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Haustür", hebrewWord: "דלת כניסה", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "der Kamin", hebrewWord: "אח", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Veranda", hebrewWord: "מרפסת מקורה", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Waschküche", hebrewWord: "חדר כביסה", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Büro", hebrewWord: "משרד", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Terrasse", hebrewWord: "טרסה", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Gästezimmer", hebrewWord: "חדר אורחים", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Vorratskammer", hebrewWord: "מזווה", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "das Badezimmer", hebrewWord: "חדר שירותים", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "House Parts", germanWord: "die Eingangshalle", hebrewWord: "אולם כניסה", knowlage: "V" , userId },

// Animals
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Hund", hebrewWord: "כלב", knowlage: "V" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Katze", hebrewWord: "חתול", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "das Pferd", hebrewWord: "סוס", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Kuh", hebrewWord: "פרה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "das Schwein", hebrewWord: "חזיר", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "das Schaf", hebrewWord: "כבשה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Ziege", hebrewWord: "עז", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Hase", hebrewWord: "ארנב", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Fuchs", hebrewWord: "שועל", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Bär", hebrewWord: "דוב", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Löwe", hebrewWord: "אריה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Tiger", hebrewWord: "טיגריס", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Elefant", hebrewWord: "פיל", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Maus", hebrewWord: "עכבר", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Vogel", hebrewWord: "ציפור", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Fisch", hebrewWord: "דג", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Schlange", hebrewWord: "נחש", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Spinne", hebrewWord: "עכביש", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Affe", hebrewWord: "קוף", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "das Känguru", hebrewWord: "קנגורו", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Delfin", hebrewWord: "דולפין", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Wal", hebrewWord: "לוויתן", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Pinguin", hebrewWord: "פינגווין", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "das Krokodil", hebrewWord: "תנין", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Schmetterling", hebrewWord: "פרפר", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Ameise", hebrewWord: "נמלה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Biene", hebrewWord: "דבורה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "der Hahn", hebrewWord: "תרנגול", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Ente", hebrewWord: "ברווז", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Animals", germanWord: "die Gans", hebrewWord: "אווז", knowlage: "X" , userId },

// Basic Emotions
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "glücklich", hebrewWord: "שמח", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "traurig", hebrewWord: "עצוב", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "wütend", hebrewWord: "כועס", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "aufgeregt", hebrewWord: "נרגש", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "ängstlich", hebrewWord: "מפוחד", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "zufrieden", hebrewWord: "מרוצה", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "überrascht", hebrewWord: "מופתע", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "gelangweilt", hebrewWord: "משועמם", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "besorgt", hebrewWord: "מודאג", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "verliebt", hebrewWord: "מאוהב", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "neidisch", hebrewWord: "מקנא", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "dankbar", hebrewWord: "מודה", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "müde", hebrewWord: "עייף", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "verärgert", hebrewWord: "כועס", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "schüchtern", hebrewWord: "ביישן", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "stolz", hebrewWord: "גאה", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "verwirrt", hebrewWord: "מבולבל", knowlage: "?" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "einsam", hebrewWord: "בודד", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "frustriert", hebrewWord: "מתוסכל", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "hoffnungsvoll", hebrewWord: "מקווה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "erschöpft", hebrewWord: "מותש", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "verletzt", hebrewWord: "נפגע", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "eifersüchtig", hebrewWord: "קנאי", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "beschämt", hebrewWord: "מתבייש", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "entspannt", hebrewWord: "רגוע", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "unwohl", hebrewWord: "לא בנוח", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "aufmerksam", hebrewWord: "קשוב", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "vergnügt", hebrewWord: "מרוצה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "hoffnungslos", hebrewWord: "חסר תקווה", knowlage: "X" , userId },
{ hebrewLevel: "מבוא" as const, englishLevel: "A1" as const, courseNameEnglish: "Basic Emotions", germanWord: "erleichtert", hebrewWord: "מוקל", knowlage: "X" , userId },

// A2
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "seasons", germanWord: "sommer", hebrewWord: "קיץ", knowlage: "X" , userId },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "seasons", germanWord: "winter", hebrewWord: "חורף", knowlage: "X" , userId },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "seasons", germanWord: "herbst", hebrewWord: "סתיו", knowlage: "X" , userId },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "seasons", germanWord: "frühling", hebrewWord: "אביב", knowlage: "?" , userId },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Apfel", hebrewWord: "תפוח", knowlage: "?" , userId },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Brot", hebrewWord: "לחם", knowlage: "?" , userId },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Milch", hebrewWord: "חלב", knowlage: "?" , userId },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Eier", hebrewWord: "ביצים", knowlage: "X" , userId },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Käse", hebrewWord: "גבינה", knowlage: "V" , userId },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Butter", hebrewWord: "חמאה", knowlage: "V" , userId },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Fleisch", hebrewWord: "בשר", knowlage: "V" , userId },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Gemüse", hebrewWord: "ירקות", knowlage: "V" , userId },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Obst", hebrewWord: "פירות", knowlage: "V" , userId },
{ hebrewLevel: "בסיסי" as const, englishLevel: "A2" as const, courseNameEnglish: "Shopping", germanWord: "Wasser", hebrewWord: "מים", knowlage: "X" , userId },

// B1
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Zeitung", hebrewWord: "עיתון", knowlage: "X" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Nachrichten", hebrewWord: "חדשות", knowlage: "X" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Reporter", hebrewWord: "כתב", knowlage: "X" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Interview", hebrewWord: "ראיון", knowlage: "X" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Artikel", hebrewWord: "מאמר", knowlage: "X" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Fernsehen", hebrewWord: "טלוויזיה", knowlage: "?" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Radio", hebrewWord: "רדיו", knowlage: "?" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Überschrift", hebrewWord: "כותרת", knowlage: "?" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Online-Medien", hebrewWord: "מדיה מקוונת", knowlage: "?" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "News and media", germanWord: "Nachrichtensprecher", hebrewWord: "מגיש חדשות", knowlage: "?" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Baum", hebrewWord: "עץ", knowlage: "?" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Fluss", hebrewWord: "נהר", knowlage: "X" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Berg", hebrewWord: "הר", knowlage: "X" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Wald", hebrewWord: "יער", knowlage: "?" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "See", hebrewWord: "אגם", knowlage: "?" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Vogel", hebrewWord: "ציפור", knowlage: "?" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Löwe", hebrewWord: "אריה", knowlage: "?" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Fisch", hebrewWord: "דג", knowlage: "?" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Blume", hebrewWord: "פרח", knowlage: "?" , userId },
{ hebrewLevel: "בינוני" as const, englishLevel: "B1" as const, courseNameEnglish: "Nature and wildlife", germanWord: "Schmetterling", hebrewWord: "פרפר", knowlage: "?" , userId },

// B2
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Freiwilliger", hebrewWord: "מתנדב", knowlage: "X" , userId },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Spende", hebrewWord: "תרומה", knowlage: "X" , userId },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Organisation", hebrewWord: "ארגון", knowlage: "X" , userId },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Hilfsprojekt", hebrewWord: "פרויקט סיוע", knowlage: "?" , userId },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Mitgefühl", hebrewWord: "אמפתיה", knowlage: "?" , userId },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Fundraising", hebrewWord: "גיוס כספים", knowlage: "?" , userId },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Gemeinschaft", hebrewWord: "קהילה", knowlage: "V" , userId },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Ehrenamt", hebrewWord: "התנדבות", knowlage: "V" , userId },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Wohltätigkeit", hebrewWord: "צדקה", knowlage: "V" , userId },
{ hebrewLevel: "מתקדם" as const, englishLevel: "B2" as const, courseNameEnglish: "Volunteerism and charity", germanWord: "Nächstenliebe", hebrewWord: "אהבת הזולת", knowlage: "X" , userId },

// C1
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Menschenrechte", hebrewWord: "זכויות אדם", knowlage: "X" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Gerechtigkeit", hebrewWord: "צדק", knowlage: "X" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Freiheit", hebrewWord: "חירות", knowlage: "X" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Diskriminierung", hebrewWord: "אפליה", knowlage: "X" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Asyl", hebrewWord: "מקלט", knowlage: "X" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Gleichheit", hebrewWord: "שוויון", knowlage: "V" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Unterdrückung", hebrewWord: "דיכוי", knowlage: "V" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Kinderarbeit", hebrewWord: "עבודת ילדים", knowlage: "V" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Meinungsfreiheit", hebrewWord: "חופש הביטוי", knowlage: "V" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Human rights issues", germanWord: "Toleranz", hebrewWord: "סובלנות", knowlage: "V" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Weltraum", hebrewWord: "חלל", knowlage: "V" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Rakete", hebrewWord: "רקטה", knowlage: "?" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Astronaut", hebrewWord: "אסטרונאוט", knowlage: "?" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Erde", hebrewWord: "כדור הארץ", knowlage: "?" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Mond", hebrewWord: "ירח", knowlage: "?" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Stern", hebrewWord: "כוכב", knowlage: "?" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Raumschiff", hebrewWord: "חללית", knowlage: "?" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Sonne", hebrewWord: "שמש", knowlage: "?" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Planeten", hebrewWord: "כוכבי לכת", knowlage: "?" , userId },
{ hebrewLevel: "מתקדם מאוד" as const, englishLevel: "C1" as const, courseNameEnglish: "Space exploration", germanWord: "Universum", hebrewWord: "יקום", knowlage: "?" , userId },

// C2
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Gehirn", hebrewWord: "מוח", knowlage: "X" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Neuron", hebrewWord: "נוירון", knowlage: "X" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Synapse", hebrewWord: "סינפסה", knowlage: "X" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Nervensystem", hebrewWord: "מערכת העצבים", knowlage: "X" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Gedächtnis", hebrewWord: "זיכרון", knowlage: "X" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Emotion", hebrewWord: "רגש", knowlage: "X" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Hirnrinde", hebrewWord: "קליפת המוח", knowlage: "?" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Refle?", hebrewWord: "רפלקס", knowlage: "?" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Motorik", hebrewWord: "מוטוריקה", knowlage: "?" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Bewusstsein", hebrewWord: "מודעות", knowlage: "?" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Kognition", hebrewWord: "קוגניציה", knowlage: "?" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Dopamin", hebrewWord: "דופמין", knowlage: "?" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Hippocampus", hebrewWord: "היפוקמפוס", knowlage: "?" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Neurotransmitter", hebrewWord: "מוליך עצבי", knowlage: "?" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Plastizität", hebrewWord: "פלסטיות", knowlage: "?" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Stress", hebrewWord: "לחץ", knowlage: "V" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Sensorik", hebrewWord: "חישה", knowlage: "V" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Verarbeitung", hebrewWord: "עיבוד", knowlage: "V" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Impuls", hebrewWord: "דחף", knowlage: "V" , userId },
{ hebrewLevel: "שפת אם" as const, englishLevel: "C2" as const, courseNameEnglish: "Neuroscience", germanWord: "Perzeption", hebrewWord: "תפיסה", knowlage: "V" , userId },
];

const getUuidByCourseName = ( courseIds: Array<{ index: number; uuid: string; courseName: string }>, courseName: string ): string => {
  const resultItem = courseIds.find((item) => item.courseName.toLowerCase() === courseName.toLowerCase());
  if (!resultItem) {
    console.error(`Course name "${courseName}" not found in courseIds`);
    console.error("Available course names:", courseIds.map((item) => item.courseName));
    throw new Error(`Course name "${courseName}" not found in courseIds`);
  }
  return resultItem.uuid;
};

const wordData = words.map((word) => ({
  ...word,
  courseId: getUuidByCourseName(courseIds, word.courseNameEnglish),
}));

await db.insert(Words).values(wordData).returning({ id: Words.courseId });
};