export class Lesson {
  private levelHebrew: string = "";
  private levelEnglish: string= "";
  private courseNameEnglish: string= "";
  private courseId: number= 0;
  private lessonId: number= 0;
  private sentenceOneGerman: string= "";
  private sentenceOneHebrew: string= "";
  private sentenceTwoGerman: string= "";
  private sentenceTwoHebrew: string= "";
  private missingSentenceOneHebrew: string= "";
  private missingWordOneHebrew: string= "";
  private missingSentenceOneGerman: string= "";
  private missingWordOneGerman: string= "";
  private missingSentenceTwoHebrew: string= "";
  private missingWordTwoHebrew: string= "";
  private missingSentenceTwoGerman: string= "";
  private missingWordTwoGerman: string= "";
  private wordOneGerman: string= "";
  private wordOneHebrew: string= "";
  private wordTwoGerman: string= "";
  private wordTwoHebrew: string= "";
  private wordThreeGerman: string= "";
  private wordThreeHebrew: string= "";
  private wordFourGerman: string= "";
  private wordFourHebrew: string= "";
  private wordFiveGerman: string= "";
  private wordFiveHebrew: string= "";
  private wordSixGerman: string= "";
  private wordSixHebrew: string= "";
  private wordSevenGerman: string= "";
  private wordSevenHebrew: string= "";
  private wordEightGerman: string= "";
  private wordEightHebrew: string= "";
  private wordNineGerman: string= "";
  private wordNineHebrew: string= "";
  private wordTenGerman: string= "";
  private wordTenHebrew: string= "";
  private wordElevenGerman: string= "";
  private wordElevenHebrew: string= "";
  private wordTwelveGerman: string= "";
  private wordTwelveHebrew: string= "";

  constructor(params: {
      levelHebrew: string;
      levelEnglish: string;
      courseNameEnglish: string;
      courseId: number;
      lessonId: number;
      sentenceOneGerman: string;
      sentenceOneHebrew: string;
      sentenceTwoGerman: string;
      sentenceTwoHebrew: string;
      missingSentenceOneHebrew: string;
      missingWordOneHebrew: string;
      missingSentenceOneGerman: string;
      missingWordOneGerman: string;
      missingSentenceTwoHebrew: string;
      missingWordTwoHebrew: string;
      missingSentenceTwoGerman: string;
      missingWordTwoGerman: string;
      wordOneGerman: string;
      wordOneHebrew: string;
      wordTwoGerman: string;
      wordTwoHebrew: string;
      wordThreeGerman: string;
      wordThreeHebrew: string;
      wordFourGerman: string;
      wordFourHebrew: string;
      wordFiveGerman: string;
      wordFiveHebrew: string;
      wordSixGerman: string;
      wordSixHebrew: string;
      wordSevenGerman: string;
      wordSevenHebrew: string;
      wordEightGerman: string;
      wordEightHebrew: string;
      wordNineGerman: string;
      wordNineHebrew: string;
      wordTenGerman: string;
      wordTenHebrew: string;
      wordElevenGerman: string;
      wordElevenHebrew: string;
      wordTwelveGerman: string;
      wordTwelveHebrew: string;
  }) {
      Object.assign(this, params);
  }
}
