import { v4 as uuidv4 } from "uuid";

export const hangmanGameId = uuidv4();
export const speedGameId = uuidv4();
export const rowGameId = uuidv4();

export const generateCourseIds = (): Array<{index: number, uuid: string, courseName: string}> => {
  const courseIds: Array<{index: number, uuid: string, courseName: string}> = [];
  for (let i = 0; i <= courseNamesArray.length; i++) {
    courseIds.push({
      index: i,
      uuid: uuidv4(),
      courseName: courseNamesArray[i],
    });
  }
  return courseIds;
};

export const courseNamesArray = [
      "Colors",
      "Numbers",
      "Family members",
      "Days of the week",
      "Months",
      "Greetings",
      "Weather" ,
      "Basic clothing",
      "Common food items",
      "House parts",
      "Animals",
      "Basic emotions",
      "Transportation",
      "School supplies",
      "Professions",
      "Body parts",
      "Hobbies",
      "Basic furniture", 
      "Sports",
      "Shapes", 
      "Time", 
      "Common places",
      "Festivals",
      "Common actions", 
      "Technology basics", 
     "Travel and transportation", 
     "Shopping", 
     "Food and drinks (advanced)",
     "Personal hygiene items", 
     "Holidays and traditions", 
     "Seasons",
     "Basic health", 
     "Daily routines",
     "Public places", 
     "Directions and locations", 
     "Modes of communication", 
     "Types of entertainment",
     "Simple adjectives", 
     "Family occasions", 
     "Simple weather terms", 
     "School subjects", 
     "Basic verbs in context",
     "Pets and farm animals",
     "Weekend activities", 
     "Cultural landmarks",
     "Tools and utensils",
     "Basic emotions and feelings",  
     "Street signs and warnings",
     "Simple financial terms",
     "Music and instruments",
     "Work and jobs", 
     "Social media and online platforms",
     "Health and fitness",
     "Environment and recycling", 
     "Technology and gadgets",
     "Travel and holidays", 
     "Education and study habits", 
     "Cultural diversity", 
     "News and media", 
     "Describing people", 
     "Celebrations and events", 
     "Hobbies and leisure activities",
     "Relationships and friendship",
     "City life and countryside", 
     "Basic politics and government terms",
     "Transportation systems",
     "Historical events", 
     "Nature and wildlife", 
     "Fashion and trends",
     "Stress management", 
     "Problem-solving scenarios", 
     "Describing feelings and thoughts",
     "Fiction and literature genres", 
     "Scientific discoveries",
     "Food culture around the world", 
  

       "Advanced travel (backpacking, ecotourism)", 
       "Economy and finance basics",
       "Global warming and climate change", 
       "Technology advancements",
       "Social issues (homelessness, inequality)", 
       "Volunteerism and charity", 
       "Science and research topics", 
       "Advanced education topics (higher education)", 
       "Historical figures and their contributions",
       "Advanced personal development",
       "Sports and international competitions",
       "Art and exhibitions", 
       "Debating topics",
       "Ethical dilemmas", 
       "Public speaking",
       "Philosophical questions", 
       "Innovations in healthcare",
       "Adventure and survival skills", 
       "Advanced emotions and psychology", 
       "Networking and communication skills",
       "Freelancing and entrepreneurship", 
       "Media and propaganda", 
       "Artificial intelligence", 
       "Fictional storytelling", 
       "Urban planning and architecture", 
    
        "International relations",
        "Advanced literary analysis",
        "Philosophy and critical thinking",
        "Advanced science topics (genetics, astronomy)",
        "Advanced environmental studies", 
        "Journalism and reporting", 
        "Social justice", 
        "Politics and policies", 
        "Historical conflicts and resolutions", 
        "Advanced art history",
        "Theater and performing arts",
        "Cultural anthropology",
        "Ethics in technology",
        "Psychology and mental health", 
        "Advanced business and economics",
        "Cryptocurrency and blockchain", 
        "Advanced debates",
        "Human rights issues", 
        "Advanced language nuances",  
        "Satire and humor in culture", 
        "Advanced education policies",
        "Space exploration",
        "Technological ethics", 
        "Advanced social media strategies", 
        "Advanced networking", 
     "Advanced geopolitics", 
     "Abstract art and symbolism",
     "Quantum physics basics",
     "Philosophy of mind", 
     "Neuroscience", 
     "Global economic policies", 
     "Advanced literary critique", 
     "Artificial intelligence ethics", 
     "Linguistic studies and etymology", 
     "Advanced environmental law", 
     "Post-modern literature",
     "International diplomacy", 
     "History of philosophy", 
     "Avant-garde music and culture", 
     "Deep learning and AI",
     "Global health crises",
     "Socio-political satire",
     "Advanced film analysis",
     "Advanced cultural studies", 
     "Advanced psychology topics (cognitive biases)",
     "Advanced persuasive techniques",
     "Sustainability in design",
     "Ethical dilemmas in modern society", 
     "Cross-cultural communication", 
     "Advanced storytelling", 
];