import { drizzle } from "drizzle-orm/node-postgres";
import { CourseNames } from "./drizzle/schema";
import {db} from "./drizzle/db";


async function seed() {
  console.log("Seeding database...");

  const items = await db.insert(CourseNames).values([
  // A1
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Colors", course_name_german: "Farben", course_name_hebrew: "צבעים", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Numbers", course_name_german: "Zahlen", course_name_hebrew: "מספרים", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Family members", course_name_german: "Familienmitglieder", course_name_hebrew: "בני משפחה", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Days of the week", course_name_german: "Wochentage", course_name_hebrew: "ימי השבוע", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Months", course_name_german: "Monate", course_name_hebrew: "חודשים", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Greetings", course_name_german: "Grüße", course_name_hebrew: "ברכות", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Weather", course_name_german: "Wetter", course_name_hebrew: "מזג האוויר", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Basic clothing", course_name_german: "Grundkleidung", course_name_hebrew: "בגדים בסיסיים", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Common food items", course_name_german: "Häufige Lebensmittel", course_name_hebrew: "מוצרי מזון נפוצים", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "House parts", course_name_german: "Hausteile", course_name_hebrew: "חלקי הבית", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Animals", course_name_german: "Tiere", course_name_hebrew: "חיות", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Basic emotions", course_name_german: "Grundgefühle", course_name_hebrew: "רגשות בסיסיות", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Transportation", course_name_german: "Transport", course_name_hebrew: "הובלה", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "School supplies", course_name_german: "Schulmaterial", course_name_hebrew: "ציודי בית הספר", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Professions", course_name_german: "Berufe", course_name_hebrew: "מקצועות", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Body parts", course_name_german: "Körperteile", course_name_hebrew: "חלקי הגוף", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Hobbies", course_name_german: "Hobbys", course_name_hebrew: "תחביבים", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Basic furniture", course_name_german: "Grundmöbel", course_name_hebrew: "רהיט בסיסיים", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Sports", course_name_german: "Sportarten", course_name_hebrew: "ספורט", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Shapes", course_name_german: "Formen", course_name_hebrew: "צורות", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Time", course_name_german: "Zeit", course_name_hebrew: "זמן", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Common places", course_name_german: "Gemeinsame Orte", course_name_hebrew: "מקומות נפוצות", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Festivals", course_name_german: "Feste", course_name_hebrew: "חגיגים", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Common actions", course_name_german: "Häufige Aktionen", course_name_hebrew: "פעולות נפוצות", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name_english: "Technology basics", course_name_german: "Technologie Grundlagen", course_name_hebrew: "טכנולוגיה בסיסית", lesson_completed: 0 },

  // A2
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Travel and transportation", course_name_german: "Reisen und Transport", course_name_hebrew: "נסיעות והובלה", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Shopping", course_name_german: "Einkaufen", course_name_hebrew: "קניות", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Food and drinks (advanced)", course_name_german: "Lebensmittel und Getränke (fortgeschritten)", course_name_hebrew: "מזון ומשקאות (מתקדם)", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Personal hygiene items", course_name_german: "Körperpflegeprodukte", course_name_hebrew: "מוצרי היגיינה אישית", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Holidays and traditions", course_name_german: "Feiertage und Traditionen", course_name_hebrew: "חגים ומסורת", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Seasons", course_name_german: "Jahreszeiten", course_name_hebrew: "עונות השנה", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Basic health", course_name_german: "Grundlegende Gesundheit", course_name_hebrew: "בריאות בריאות", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Daily routines", course_name_german: "Tagesabläufe", course_name_hebrew: "שגרות יומיות", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Public places", course_name_german: "Öffentliche Orte", course_name_hebrew: "מקומות ציבוריות", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Directions and locations", course_name_german: "Richtungen und Standorte", course_name_hebrew: "כיוונים ומיקומים", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Modes of communication", course_name_german: "Kommunikationsmittel", course_name_hebrew: "אמצעי תקשורת", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Types of entertainment", course_name_german: "Unterhaltungsarten", course_name_hebrew: "סוגיות בידור", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Simple adjectives", course_name_german: "Einfache Adjektive", course_name_hebrew: "תארים פשוטים", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Family occasions", course_name_german: "Familienanlässe", course_name_hebrew: "אירועי משפחה", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Simple weather terms", course_name_german: "Einfache Wetterbegriffe", course_name_hebrew: "מונחים פשוטים על מזג אוויר", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "School subjects", course_name_german: "Schulfächer", course_name_hebrew: "תמודות בבית הספר", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Basic verbs in context", course_name_german: "Grundlegende Verben im Kontext", course_name_hebrew: "פעלים בסיסיים המתאמים", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Pets and farm animals", course_name_german: "Haustiere und Nutztiere", course_name_hebrew: "חיות משק ובעלי משק", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Weekend activities", course_name_german: "Wochenendaktivitäten", course_name_hebrew: "פעילות לסופשים", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Cultural landmarks", course_name_german: "Kulturelle Wahrzeichen", course_name_hebrew: "אתרי תרבות", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Tools and utensils", course_name_german: "Werkzeuge und Utensilien", course_name_hebrew: "כליים וכלי מטבח", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Basic emotions and feelings", course_name_german: "Grundlegende Emotionen und Gefühle", course_name_hebrew: "רגשות בסיסיות", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Street signs and warnings", course_name_german: "Straßenschilder und Warnungen", course_name_hebrew: "שילוטי בעלים ואזרות", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Simple financial terms", course_name_german: "Einfache Finanzbegriffe", course_name_hebrew: "מונחים כלכליים פשוטים", lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name_english: "Music and instruments", course_name_german: "Musik und Instrumente", course_name_hebrew: "מוזיקה וכליי נגינה", lesson_completed: 0 },


  // B1
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Work and jobs", course_name_german: "Arbeit und Berufe", course_name_hebrew: "עבודה ומקצועות", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Social media and online platforms", course_name_german: "Soziale Medien und Online-Plattformen", course_name_hebrew: "מדיה חברתית ופלטפורמות מקוונות", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Health and fitness", course_name_german: "Gesundheit und Fitness", course_name_hebrew: "בריאות וכושר", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Environment and recycling", course_name_german: "Umwelt und Recycling", course_name_hebrew: "סביבה ומיחזור", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Technology and gadgets", course_name_german: "Technologie und Geräte", course_name_hebrew: "טכנולוגיה וגאדג'טים", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Travel and holidays", course_name_german: "Reisen und Ferien", course_name_hebrew: "נסיעות וחופשות", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Education and study habits", course_name_german: "Bildung und Lerngewohnheiten", course_name_hebrew: "חינוך והרגלי לימוד", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Cultural diversity", course_name_german: "Kulturelle Vielfalt", course_name_hebrew: "גיוון תרבותי", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "News and media", course_name_german: "Nachrichten und Medien", course_name_hebrew: "חדשות ומדיה", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Describing people", course_name_german: "Menschen beschreiben", course_name_hebrew: "תיאור אנשים", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Celebrations and events", course_name_german: "Feiern und Veranstaltungen", course_name_hebrew: "חגיגות ואירועים", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Hobbies and leisure activities", course_name_german: "Hobbys und Freizeitaktivitäten", course_name_hebrew: "תחביבים ופעילויות פנאי", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Relationships and friendship", course_name_german: "Beziehungen und Freundschaft", course_name_hebrew: "מערכות יחסים וחברות", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "City life and countryside", course_name_german: "Stadtleben und Land", course_name_hebrew: "חיי עיר וכפר", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Basic politics and government terms", course_name_german: "Grundlagen der Politik und Regierung", course_name_hebrew: "מונחים בסיסיים בפוליטיקה וממשל", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Transportation systems", course_name_german: "Verkehrssysteme", course_name_hebrew: "מערכות תחבורה", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Historical events", course_name_german: "Historische Ereignisse", course_name_hebrew: "אירועים היסטוריים", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Nature and wildlife", course_name_german: "Natur und Wildtiere", course_name_hebrew: "טבע וחיות בר", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Fashion and trends", course_name_german: "Mode und Trends", course_name_hebrew: "אופנה וטרנדים", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Stress management", course_name_german: "Stressbewältigung", course_name_hebrew: "ניהול מתח", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Problem-solving scenarios", course_name_german: "Problemlösungs-Szenarien", course_name_hebrew: "תרחישי פתרון בעיות", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Describing feelings and thoughts", course_name_german: "Gefühle und Gedanken beschreiben", course_name_hebrew: "תיאור רגשות ומחשבות", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Fiction and literature genres", course_name_german: "Fiktion und Literaturgenres", course_name_hebrew: "ז'אנרים בספרות ובדמיון", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Scientific discoveries", course_name_german: "Wissenschaftliche Entdeckungen", course_name_hebrew: "תגליות מדעיות", lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name_english: "Food culture around the world", course_name_german: "Esskultur weltweit", course_name_hebrew: "תרבות אוכל מסביב לעולם", lesson_completed: 0 },


    // B2
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Advanced travel (backpacking, ecotourism)", course_name_german: "Fortgeschrittenes Reisen (Rucksackreisen, Ökotourismus)", course_name_hebrew: "נסיעות מתקדמות (טיולים עם תרמיל, תיירות אקולוגית)", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Economy and finance basics", course_name_german: "Grundlagen der Wirtschaft und Finanzen", course_name_hebrew: "יסודות הכלכלה והפיננסים", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Global warming and climate change", course_name_german: "Globale Erwärmung und Klimawandel", course_name_hebrew: "התחממות כדור הארץ ושינויי אקלים", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Technology advancements", course_name_german: "Technologische Fortschritte", course_name_hebrew: "התפתחויות טכנולוגיות", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Social issues (homelessness, inequality)", course_name_german: "Soziale Probleme (Obdachlosigkeit, Ungleichheit)", course_name_hebrew: "בעיות חברתיות (חוסר בית, אי שוויון)", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Volunteerism and charity", course_name_german: "Ehrenamt und Wohltätigkeit", course_name_hebrew: "התנדבות וצדקה", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Science and research topics", course_name_german: "Wissenschaft und Forschungsthemen", course_name_hebrew: "מדע ונושאי מחקר", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Advanced education topics (higher education)", course_name_german: "Fortgeschrittene Bildungsthemen (Hochschulbildung)", course_name_hebrew: "נושאי חינוך מתקדמים (השכלה גבוהה)", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Historical figures and their contributions", course_name_german: "Historische Persönlichkeiten und ihre Beiträge", course_name_hebrew: "דמויות היסטוריות ותרומותיהן", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Advanced personal development", course_name_german: "Fortgeschrittene persönliche Entwicklung", course_name_hebrew: "התפתחות אישית מתקדמת", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Sports and international competitions", course_name_german: "Sport und internationale Wettbewerbe", course_name_hebrew: "ספורט ותחרויות בינלאומיות", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Art and exhibitions", course_name_german: "Kunst und Ausstellungen", course_name_hebrew: "אמנות ותערוכות", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Debating topics", course_name_german: "Debattenthemen", course_name_hebrew: "נושאי ויכוח", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Ethical dilemmas", course_name_german: "Ethische Dilemmata", course_name_hebrew: "דילמות אתיות", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Public speaking", course_name_german: "Öffentliches Reden", course_name_hebrew: "דיבור בפני קהל", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Philosophical questions", course_name_german: "Philosophische Fragen", course_name_hebrew: "שאלות פילוסופיות", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Innovations in healthcare", course_name_german: "Innovationen im Gesundheitswesen", course_name_hebrew: "חידושים בתחום הבריאות", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Adventure and survival skills", course_name_german: "Abenteuer- und Überlebensfähigkeiten", course_name_hebrew: "הרפתקאות וכישורי הישרדות", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Advanced emotions and psychology", course_name_german: "Fortgeschrittene Emotionen und Psychologie", course_name_hebrew: "רגשות מתקדמים ופסיכולוגיה", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Networking and communication skills", course_name_german: "Netzwerk- und Kommunikationsfähigkeiten", course_name_hebrew: "כישורי רשת ותקשורת", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Freelancing and entrepreneurship", course_name_german: "Freiberuflichkeit und Unternehmertum", course_name_hebrew: "עבודה כפרילנס ויזמות", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Media and propaganda", course_name_german: "Medien und Propaganda", course_name_hebrew: "מדיה ותעמולה", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Artificial intelligence", course_name_german: "Künstliche Intelligenz", course_name_hebrew: "בינה מלאכותית", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Fictional storytelling", course_name_german: "Fiktionales Erzählen", course_name_hebrew: "סיפורת בדיונית", lesson_completed: 0 },
    { level_english: "B2", level_hebrew: "מתקדם", course_name_english: "Urban planning and architecture", course_name_german: "Stadtplanung und Architektur", course_name_hebrew: "תכנון עירוני ואדריכלות", lesson_completed: 0 },
  
    // C1
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "International relations", course_name_german: "Internationale Beziehungen", course_name_hebrew: "יחסים בינלאומיים", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Advanced literary analysis", course_name_german: "Fortgeschrittene literarische Analyse", course_name_hebrew: "ניתוח ספרותי מתקדם", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Philosophy and critical thinking", course_name_german: "Philosophie und kritisches Denken", course_name_hebrew: "פילוסופיה וחשיבה ביקורתית", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Advanced science topics (genetics, astronomy)", course_name_german: "Fortgeschrittene Wissenschaftsthemen (Genetik, Astronomie)", course_name_hebrew: "נושאים מדעיים מתקדמים (גנטיקה, אסטרונומיה)", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Advanced environmental studies", course_name_german: "Fortgeschrittene Umweltstudien", course_name_hebrew: "לימודי סביבה מתקדמים", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Journalism and reporting", course_name_german: "Journalismus und Berichterstattung", course_name_hebrew: "עיתונאות ודיווח", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Social justice", course_name_german: "Soziale Gerechtigkeit", course_name_hebrew: "צדק חברתי", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Politics and policies", course_name_german: "Politik und Richtlinien", course_name_hebrew: "פוליטיקה ומדיניות", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Historical conflicts and resolutions", course_name_german: "Historische Konflikte und Lösungen", course_name_hebrew: "קונפליקטים והסדרים היסטוריים", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Advanced art history", course_name_german: "Fortgeschrittene Kunstgeschichte", course_name_hebrew: "היסטוריה של האמנות המתקדמת", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Theater and performing arts", course_name_german: "Theater und darstellende Künste", course_name_hebrew: "תיאטרון ואמנויות הבמה", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Cultural anthropology", course_name_german: "Kulturelle Anthropologie", course_name_hebrew: "אנתרופולוגיה תרבותית", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Ethics in technology", course_name_german: "Ethik in der Technologie", course_name_hebrew: "אתיקה בטכנולוגיה", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Psychology and mental health", course_name_german: "Psychologie und psychische Gesundheit", course_name_hebrew: "פסיכולוגיה ובריאות הנפש", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Advanced business and economics", course_name_german: "Fortgeschrittenes Geschäft und Wirtschaft", course_name_hebrew: "עסקים וכלכלה מתקדמים", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Cryptocurrency and blockchain", course_name_german: "Kryptowährung und Blockchain", course_name_hebrew: "מטבעות קריפטוגרפיים ובלוקצ'יין", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Advanced debates", course_name_german: "Fortgeschrittene Debatten", course_name_hebrew: "דיונים מתקדמים", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Human rights issues", course_name_german: "Menschenrechtsfragen", course_name_hebrew: "סוגיות זכויות אדם", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Advanced language nuances", course_name_german: "Fortgeschrittene Sprachnuancen", course_name_hebrew: "ניואנסים בשפה מתקדמת", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Satire and humor in culture", course_name_german: "Satire und Humor in der Kultur", course_name_hebrew: "סטירה והומור בתרבות", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Advanced education policies", course_name_german: "Fortgeschrittene Bildungspolitik", course_name_hebrew: "מדיניות חינוך מתקדמת", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Space exploration", course_name_german: "Weltraumforschung", course_name_hebrew: "חקר החלל", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Technological ethics", course_name_german: "Technologische Ethik", course_name_hebrew: "אתיקה טכנולוגית", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Advanced social media strategies", course_name_german: "Fortgeschrittene Strategien für soziale Medien", course_name_hebrew: "אסטרטגיות מתקדמות במדיה חברתית", lesson_completed: 0 },
    { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name_english: "Advanced networking", course_name_german: "Fortgeschrittene Netzwerke", course_name_hebrew: "רישות מתקדם", lesson_completed: 0 },
  

  // C2
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Advanced geopolitics", course_name_german: "Fortgeschrittene Geopolitik", course_name_hebrew: "גאופוליטיקה מתקדמת", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Abstract art and symbolism", course_name_german: "Abstrakte Kunst und Symbolik", course_name_hebrew: "אמנות מופשטת וסמליות", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Quantum physics basics", course_name_german: "Grundlagen der Quantenphysik", course_name_hebrew: "יסודות הפיזיקה הקוונטית", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Philosophy of mind", course_name_german: "Philosophie des Geistes", course_name_hebrew: "פילוסופיית הנפש", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Neuroscience", course_name_german: "Neurowissenschaft", course_name_hebrew: "מדעי המוח", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Global economic policies", course_name_german: "Globale Wirtschaftspolitik", course_name_hebrew: "מדיניות כלכלית גלובלית", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Advanced literary critique", course_name_german: "Fortgeschrittene Literaturkritik", course_name_hebrew: "ביקורת ספרותית מתקדמת", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Artificial intelligence ethics", course_name_german: "Ethik der künstlichen Intelligenz", course_name_hebrew: "אתיקה של בינה מלאכותית", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Linguistic studies and etymology", course_name_german: "Linguistische Studien und Etymologie", course_name_hebrew: "לימודי בלשנות ואטימולוגיה", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Advanced environmental law", course_name_german: "Fortgeschrittenes Umweltrecht", course_name_hebrew: "משפט סביבתי מתקדם", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Post-modern literature", course_name_german: "Postmoderne Literatur", course_name_hebrew: "ספרות פוסט-מודרנית", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "International diplomacy", course_name_german: "Internationale Diplomatie", course_name_hebrew: "דיפלומטיה בינלאומית", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "History of philosophy", course_name_german: "Geschichte der Philosophie", course_name_hebrew: "היסטוריה של פילוסופיה", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Avant-garde music and culture", course_name_german: "Avantgarde-Musik und Kultur", course_name_hebrew: "מוזיקה ותרבות אוונגרדית", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Deep learning and AI", course_name_german: "Deep Learning und KI", course_name_hebrew: "למידה עמוקה ובינה מלאכותית", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Global health crises", course_name_german: "Globale Gesundheitskrisen", course_name_hebrew: "משברים בריאותיים גלובליים", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Socio-political satire", course_name_german: "Soziopolitische Satire", course_name_hebrew: "סטירה חברתית-פוליטית", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Advanced film analysis", course_name_german: "Fortgeschrittene Filmanalyse", course_name_hebrew: "ניתוח קולנוע מתקדם", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Advanced cultural studies", course_name_german: "Fortgeschrittene Kulturwissenschaften", course_name_hebrew: "לימודי תרבות מתקדמים", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Advanced psychology topics (cognitive biases)", course_name_german: "Fortgeschrittene Psychologiethemen (kognitive Verzerrungen)", course_name_hebrew: "נושאים מתקדמים בפסיכולוגיה (הטיות קוגניטיביות)", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Advanced persuasive techniques", course_name_german: "Fortgeschrittene Überzeugungstechniken", course_name_hebrew: "טכניקות שכנוע מתקדמות", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Sustainability in design", course_name_german: "Nachhaltigkeit im Design", course_name_hebrew: "קיימות בעיצוב", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Ethical dilemmas in modern society", course_name_german: "Ethische Dilemmata in der modernen Gesellschaft", course_name_hebrew: "דילמות אתיות בחברה המודרנית", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Cross-cultural communication", course_name_german: "Interkulturelle Kommunikation", course_name_hebrew: "תקשורת בין-תרבותית", lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name_english: "Advanced storytelling", course_name_german: "Fortgeschrittenes Geschichtenerzählen", course_name_hebrew: "סיפור סיפורים מתקדם", lesson_completed: 0 },
  ]).returning({ id: CourseNames.id });
}

seed().catch((error) => {
  console.error("Error during seeding:", error);
  process.exit(1);
});