import { drizzle } from "drizzle-orm/node-postgres";
import { CourseNames } from "./drizzle/schema";
import {db} from "./drizzle/db";


async function seed() {
  console.log("Seeding database...");

  const items = await db.insert(CourseNames).values([
  // A1
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Colors" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Numbers" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Family members" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Days of the week" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Months" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Greetings" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Weather" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Basic clothing" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Common food items" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "House parts" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Animals" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Basic emotions" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Transportation" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "School supplies" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Professions" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Body parts" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Hobbies" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Basic furniture" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Sports" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Shapes" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Time" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Common places" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Festivals" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Common actions" },
  { level_english: "A1", level_hebrew: "מבוא", courseName: "Technology basics" },

  // A2
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Travel and transportation" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Shopping" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Food and drinks (advanced)" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Personal hygiene items" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Holidays and traditions" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Seasons" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Basic health" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Daily routines" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Public places" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Directions and locations" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Modes of communication" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Types of entertainment" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Simple adjectives" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Family occasions" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Simple weather terms" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "School subjects" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Basic verbs in context" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Pets and farm animals" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Weekend activities" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Cultural landmarks" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Tools and utensils" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Basic emotions and feelings" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Street signs and warnings" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Simple financial terms" },
  { level_english: "A2", level_hebrew: "בסיסי", courseName: "Music and instruments" },

  // B1
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Work and jobs" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Social media and online platforms" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Health and fitness" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Environment and recycling" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Technology and gadgets" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Travel and holidays" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Education and study habits" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Cultural diversity" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "News and media" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Describing people" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Celebrations and events" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Hobbies and leisure activities" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Relationships and friendship" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "City life and countryside" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Basic politics and government terms" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Transportation systems" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Historical events" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Nature and wildlife" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Fashion and trends" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Stress management" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Problem-solving scenarios" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Describing feelings and thoughts" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Fiction and literature genres" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Scientific discoveries" },
  { level_english: "B1", level_hebrew: "בינוני", courseName: "Food culture around the world" },

  // B2
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Advanced travel (backpacking, ecotourism)" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Economy and finance basics" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Global warming and climate change" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Technology advancements" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Social issues (homelessness, inequality)" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Volunteerism and charity" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Science and research topics" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Advanced education topics (higher education)" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Historical figures and their contributions" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Advanced personal development" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Sports and international competitions" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Art and exhibitions" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Debating topics" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Ethical dilemmas" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Public speaking" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Philosophical questions" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Innovations in healthcare" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Adventure and survival skills" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Advanced emotions and psychology" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Networking and communication skills" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Freelancing and entrepreneurship" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Media and propaganda" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Artificial intelligence" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Fictional storytelling" },
  { level_english: "B2", level_hebrew: "מתקדם", courseName: "Urban planning and architecture" },

  // C1
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "International relations" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Advanced literary analysis" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Philosophy and critical thinking" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Advanced science topics (genetics, astronomy)" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Advanced environmental studies" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Journalism and reporting" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Social justice" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Politics and policies" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Historical conflicts and resolutions" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Advanced art history" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Theater and performing arts" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Cultural anthropology" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Ethics in technology" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Psychology and mental health" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Advanced business and economics" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Cryptocurrency and blockchain" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Advanced debates" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Human rights issues" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Advanced language nuances" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Satire and humor in culture" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Advanced education policies" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Space exploration" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Technological ethics" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Advanced social media strategies" },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", courseName: "Advanced networking" },

  // C2
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Advanced geopolitics" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Abstract art and symbolism" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Quantum physics basics" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Philosophy of mind" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Neuroscience" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Global economic policies" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Advanced literary critique" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Artificial intelligence ethics" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Linguistic studies and etymology" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Advanced environmental law" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Post-modern literature" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "International diplomacy" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "History of philosophy" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Avant-garde music and culture" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Deep learning and AI" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Global health crises" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Socio-political satire" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Advanced film analysis" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Advanced cultural studies" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Advanced psychology topics (cognitive biases)" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Advanced persuasive techniques" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Sustainability in design" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Ethical dilemmas in modern society" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Cross-cultural communication" },
  { level_english: "C2", level_hebrew: "שפת אם", courseName: "Advanced storytelling" },
  ]).returning({ id: CourseNames.id });
}

seed().catch((error) => {
  console.error("Error during seeding:", error);
  process.exit(1);
});