import { drizzle } from "drizzle-orm/node-postgres";
import { CourseNames } from "./drizzle/schema";
import {db} from "./drizzle/db";


async function seed() {
  console.log("Seeding database...");

  const items = await db.insert(CourseNames).values([
  // A1
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Colors", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Numbers", lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Family members" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Days of the week" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Months" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Greetings" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Weather" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Basic clothing" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Common food items" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "House parts" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Animals" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Basic emotions" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Transportation" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "School supplies" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Professions" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Body parts" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Hobbies" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Basic furniture" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Sports" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Shapes" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Time" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Common places" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Festivals" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Common actions" , lesson_completed: 0 },
  { level_english: "A1", level_hebrew: "מבוא", course_name: "Technology basics" , lesson_completed: 0 },

  // A2
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Travel and transportation" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Shopping" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Food and drinks (advanced)" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Personal hygiene items" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Holidays and traditions" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Seasons" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Basic health" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Daily routines" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Public places" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Directions and locations" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Modes of communication" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Types of entertainment" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Simple adjectives" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Family occasions" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Simple weather terms" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "School subjects" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Basic verbs in context" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Pets and farm animals" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Weekend activities" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Cultural landmarks" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Tools and utensils" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Basic emotions and feelings" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Street signs and warnings" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Simple financial terms" , lesson_completed: 0 },
  { level_english: "A2", level_hebrew: "בסיסי", course_name: "Music and instruments" , lesson_completed: 0 },

  // B1
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Work and jobs" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Social media and online platforms" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Health and fitness" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Environment and recycling" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Technology and gadgets" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Travel and holidays" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Education and study habits" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Cultural diversity" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "News and media" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Describing people" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Celebrations and events" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Hobbies and leisure activities" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Relationships and friendship" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "City life and countryside" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Basic politics and government terms" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Transportation systems" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Historical events" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Nature and wildlife" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Fashion and trends" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Stress management" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Problem-solving scenarios" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Describing feelings and thoughts" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Fiction and literature genres" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Scientific discoveries" , lesson_completed: 0 },
  { level_english: "B1", level_hebrew: "בינוני", course_name: "Food culture around the world" , lesson_completed: 0 },

  // B2
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Advanced travel (backpacking, ecotourism)" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Economy and finance basics" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Global warming and climate change" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Technology advancements" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Social issues (homelessness, inequality)" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Volunteerism and charity" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Science and research topics" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Advanced education topics (higher education)" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Historical figures and their contributions" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Advanced personal development" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Sports and international competitions" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Art and exhibitions" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Debating topics" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Ethical dilemmas" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Public speaking" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Philosophical questions" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Innovations in healthcare" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Adventure and survival skills" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Advanced emotions and psychology" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Networking and communication skills" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Freelancing and entrepreneurship" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Media and propaganda" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Artificial intelligence" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Fictional storytelling" , lesson_completed: 0 },
  { level_english: "B2", level_hebrew: "מתקדם", course_name: "Urban planning and architecture" , lesson_completed: 0 },

  // C1
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "International relations" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Advanced literary analysis" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Philosophy and critical thinking" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Advanced science topics (genetics, astronomy)" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Advanced environmental studies" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Journalism and reporting" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Social justice" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Politics and policies" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Historical conflicts and resolutions" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Advanced art history" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Theater and performing arts" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Cultural anthropology" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Ethics in technology" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Psychology and mental health" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Advanced business and economics" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Cryptocurrency and blockchain" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Advanced debates" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Human rights issues" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Advanced language nuances" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Satire and humor in culture" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Advanced education policies" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Space exploration" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Technological ethics" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Advanced social media strategies" , lesson_completed: 0 },
  { level_english: "C1", level_hebrew: "מתקדם מאוד", course_name: "Advanced networking" , lesson_completed: 0 },

  // C2
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Advanced geopolitics" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Abstract art and symbolism" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Quantum physics basics" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Philosophy of mind" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Neuroscience" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Global economic policies" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Advanced literary critique" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Artificial intelligence ethics" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Linguistic studies and etymology" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Advanced environmental law" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Post-modern literature" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "International diplomacy" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "History of philosophy" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Avant-garde music and culture" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Deep learning and AI" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Global health crises" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Socio-political satire" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Advanced film analysis" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Advanced cultural studies" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Advanced psychology topics (cognitive biases)" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Advanced persuasive techniques" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Sustainability in design" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Ethical dilemmas in modern society" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Cross-cultural communication" , lesson_completed: 0 },
  { level_english: "C2", level_hebrew: "שפת אם", course_name: "Advanced storytelling" , lesson_completed: 0 },
  ]).returning({ id: CourseNames.id });
}

seed().catch((error) => {
  console.error("Error during seeding:", error);
  process.exit(1);
});