import { drizzle } from "drizzle-orm/node-postgres";
import { Words } from "./drizzle/schema";
import { db } from "./drizzle/db";

async function seed() {
  try {
    console.log("Seeding database...");

    const items = await db.insert(Words).values([
    // Colors
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "rot", HebrewWord: "אדום" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "blau", HebrewWord: "כחול" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "grün", HebrewWord: "ירוק" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "gelb", HebrewWord: "צהוב" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "schwarz", HebrewWord: "שחור" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "weiß", HebrewWord: "לבן" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "grau", HebrewWord: "אפור" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "braun", HebrewWord: "חום" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "rosa", HebrewWord: "ורוד" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "orange", HebrewWord: "כתום" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "lila", HebrewWord: "סגול" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "hellblau", HebrewWord: "תכלת" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "dunkelgrün", HebrewWord: "ירוק כהה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "beige", HebrewWord: "בז'" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "violett", HebrewWord: "ארגמן" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "gold", HebrewWord: "זהב" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "silber", HebrewWord: "כסף" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "zinnober", HebrewWord: "אדמדם" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "kupfer", HebrewWord: "נחושת" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "karmin", HebrewWord: "קרמין" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "oliv", HebrewWord: "זית" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "türkis", HebrewWord: "טורקיז" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "indigo", HebrewWord: "אינדיגו" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "karmesinrot", HebrewWord: "אדום קרמזין" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "smaragdgrün", HebrewWord: "ירוק אזמרגד" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "bernstein", HebrewWord: "ענבר" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "mahagoni", HebrewWord: "מהגוני" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "schneeweiß", HebrewWord: "לבן שלג" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "kohlrabenschwarz", HebrewWord: "שחור כזפת" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 1, courseName: "Colors", GermanWord: "kakao", HebrewWord: "קקאו" },

    // Numbers
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "eins", HebrewWord: "אחד" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "zwei", HebrewWord: "שתיים" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "drei", HebrewWord: "שלוש" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "vier", HebrewWord: "ארבע" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "fünf", HebrewWord: "חמש" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "sechs", HebrewWord: "שש" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "sieben", HebrewWord: "שבע" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "acht", HebrewWord: "שמונה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "neun", HebrewWord: "תשע" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "zehn", HebrewWord: "עשר" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "elf", HebrewWord: "אחד עשרה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "zwölf", HebrewWord: "שתים עשרה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "dreizehn", HebrewWord: "שלוש עשרה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "vierzehn", HebrewWord: "ארבע עשרה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "fünfzehn", HebrewWord: "חמש עשרה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "sechzehn", HebrewWord: "שש עשרה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "siebzehn", HebrewWord: "שבע עשרה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "achtzehn", HebrewWord: "שמונה עשרה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "neunzehn", HebrewWord: "תשע עשרה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "zwanzig", HebrewWord: "עשרים" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "einundzwanzig", HebrewWord: "עשרים ואחד" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "zweiundzwanzig", HebrewWord: "עשרים ושתיים" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "dreiundzwanzig", HebrewWord: "עשרים ושלוש" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "vierundzwanzig", HebrewWord: "עשרים וארבע" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "fünfundzwanzig", HebrewWord: "עשרים וחמש" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "sechsundzwanzig", HebrewWord: "עשרים ושש" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "siebenundzwanzig", HebrewWord: "עשרים ושבע" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "achtundzwanzig", HebrewWord: "עשרים ושמונה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "neunundzwanzig", HebrewWord: "עשרים ותשע" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 2, courseName: "Numbers", GermanWord: "dreißig", HebrewWord: "שלושים" },

    // Fammily Members
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Vater", HebrewWord: "אבא" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Mutter", HebrewWord: "אמא" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Bruder", HebrewWord: "אח" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Schwester", HebrewWord: "אחות" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Opa", HebrewWord: "סבא" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Oma", HebrewWord: "סבתא" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Onkel", HebrewWord: "דוד" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Tante", HebrewWord: "דודה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Cousin", HebrewWord: "בן דוד" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Cousine", HebrewWord: "בת דוד" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Neffe", HebrewWord: "אחיין" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Nichte", HebrewWord: "אחיינית" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Enkel", HebrewWord: "נכד" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Enkelin", HebrewWord: "נכדה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Schwager", HebrewWord: "גיס" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Schwägerin", HebrewWord: "גיסה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Schwiegervater", HebrewWord: "חותן" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Schwiegermutter", HebrewWord: "חמות" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Schwiegersohn", HebrewWord: "חתן" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Schwiegertochter", HebrewWord: "כלה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Ehemann", HebrewWord: "בעל" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Ehefrau", HebrewWord: "אשה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Sohn", HebrewWord: "בן" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Tochter", HebrewWord: "בת" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Großvater", HebrewWord: "סבא רבא" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Großmutter", HebrewWord: "סבתא רבתא" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Urenkel", HebrewWord: "נין" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Urenkelin", HebrewWord: "נינה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Halbbruder", HebrewWord: "אח למחצה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 3, courseName: "Family members", GermanWord: "Halbschwester", HebrewWord: "אחות למחצה" },

    // Days of the Week
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Montag", HebrewWord: "יום שני" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Dienstag", HebrewWord: "יום שלישי" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Mittwoch", HebrewWord: "יום רביעי" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Donnerstag", HebrewWord: "יום חמישי" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Freitag", HebrewWord: "יום שישי" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Samstag", HebrewWord: "שבת" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Sonntag", HebrewWord: "יום ראשון" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Wochenbeginn", HebrewWord: "תחילת שבוע" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Wochenende", HebrewWord: "סוף שבוע" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Montagmorgen", HebrewWord: "בוקר יום שני" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Dienstagabend", HebrewWord: "ערב יום שלישי" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Mittwochnachmittag", HebrewWord: "אחר הצהריים של יום רביעי" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Donnerstagnacht", HebrewWord: "לילה של יום חמישי" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Freitagmorgen", HebrewWord: "בוקר יום שישי" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Samstagabend", HebrewWord: "ערב שבת" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Sonntagvormittag", HebrewWord: "לפני הצהריים של יום ראשון" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Erster Tag", HebrewWord: "יום ראשון" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Letzter Tag", HebrewWord: "יום אחרון" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Arbeitstag", HebrewWord: "יום עבודה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Ruhetag", HebrewWord: "יום מנוחה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Gestern", HebrewWord: "אתמול" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Heute", HebrewWord: "היום" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Morgen", HebrewWord: "מחר" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Früher", HebrewWord: "לפני כן" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Später", HebrewWord: "אחרי כן" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Nächste Woche", HebrewWord: "שבוע הבא" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Letzte Woche", HebrewWord: "שבוע שעבר" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Zukunftstag", HebrewWord: "יום בעתיד" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Vergangener Tag", HebrewWord: "יום שעבר" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 4, courseName: "Days of the Week", GermanWord: "Freie Tage", HebrewWord: "ימי חופשה" },

    // Months
    { level_hebrew: "מבוא", level_english: "A1", courseId: 5, courseName: "Months", GermanWord: "Januar", HebrewWord: "ינואר" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 5, courseName: "Months", GermanWord: "Februar", HebrewWord: "פברואר" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 5, courseName: "Months", GermanWord: "März", HebrewWord: "מרץ" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 5, courseName: "Months", GermanWord: "April", HebrewWord: "אפריל" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 5, courseName: "Months", GermanWord: "Mai", HebrewWord: "מאי" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 5, courseName: "Months", GermanWord: "Juni", HebrewWord: "יוני" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 5, courseName: "Months", GermanWord: "Juli", HebrewWord: "יולי" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 5, courseName: "Months", GermanWord: "August", HebrewWord: "אוגוסט" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 5, courseName: "Months", GermanWord: "September", HebrewWord: "ספטמבר" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 5, courseName: "Months", GermanWord: "Oktober", HebrewWord: "אוקטובר" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 5, courseName: "Months", GermanWord: "November", HebrewWord: "נובמבר" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 5, courseName: "Months", GermanWord: "Dezember", HebrewWord: "דצמבר" },

    // Greetings
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Hallo", HebrewWord: "שלום" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Guten Morgen", HebrewWord: "בוקר טוב" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Guten Tag", HebrewWord: "צהריים טובים" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Guten Abend", HebrewWord: "ערב טוב" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Gute Nacht", HebrewWord: "לילה טוב" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Wie geht's?", HebrewWord: "מה שלומך?" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Auf Wiedersehen", HebrewWord: "להתראות" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Tschüss", HebrewWord: "ביי" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Bis bald", HebrewWord: "נתראה בקרוב" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Herzlich willkommen", HebrewWord: "ברוך הבא" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Schönen Tag noch", HebrewWord: "שיהיה לך יום נעים" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Viel Glück", HebrewWord: "בהצלחה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Alles Gute", HebrewWord: "כל טוב" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Guten Appetit", HebrewWord: "בתיאבון" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Schlaf gut", HebrewWord: "שינה טובה" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Grüß Gott", HebrewWord: "ברך את ה'" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Moin", HebrewWord: "שלום (צפון גרמניה)" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Servus", HebrewWord: "שלום (דרום גרמניה)" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Prost", HebrewWord: "לחיים" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Schönen Abend noch", HebrewWord: "שיהיה לך ערב נעים" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Ich wünsche dir einen schönen Tag", HebrewWord: "אני מאחל לך יום נעים" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Bis später", HebrewWord: "נתראה מאוחר יותר" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Bis morgen", HebrewWord: "נתראה מחר" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Bis nächste Woche", HebrewWord: "נתראה בשבוע הבא" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Schön dich zu sehen", HebrewWord: "נחמד לראות אותך" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Es freut mich, dich zu treffen", HebrewWord: "שמחתי לפגוש אותך" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Ich freue mich, Sie zu sehen", HebrewWord: "שמחתי לראות אותך (רשמי)" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Ich hoffe, es geht dir gut", HebrewWord: "אני מקווה שאתה בסדר" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Herzlichen Glückwunsch", HebrewWord: "מזל טוב" },
    { level_hebrew: "מבוא", level_english: "A1", courseId: 6, courseName: "Greetings", GermanWord: "Frohes neues Jahr", HebrewWord: "שנה טובה" },

    // Weather
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es ist sonnig", HebrewWord: "יש שמש" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es ist wolkig", HebrewWord: "מעונן" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es regnet", HebrewWord: "יורד גשם" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es schneit", HebrewWord: "יורד שלג" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es ist windig", HebrewWord: "יש רוח" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es ist heiß", HebrewWord: "חם" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es ist kalt", HebrewWord: "קר" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es ist neblig", HebrewWord: "יש ערפל" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es ist stürmisch", HebrewWord: "סוער" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es ist trocken", HebrewWord: "יבש" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es ist nass", HebrewWord: "רטוב" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es gibt Gewitter", HebrewWord: "יש סופת רעמים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es ist warm", HebrewWord: "חמים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es ist kühl", HebrewWord: "קריר" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es ist wechselhaft", HebrewWord: "משתנה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es gibt einen Regenbogen", HebrewWord: "יש קשת בענן" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es hagelt", HebrewWord: "יורד ברד" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Der Himmel ist klar", HebrewWord: "השמיים בהירים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Der Himmel ist bedeckt", HebrewWord: "השמיים מכוסים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es gibt eine Hitzewelle", HebrewWord: "יש גל חום" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es gibt eine Kältewelle", HebrewWord: "יש גל קור" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es gibt starken Wind", HebrewWord: "יש רוח חזקה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es gibt dichten Nebel", HebrewWord: "יש ערפל כבד" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es ist bewölkt", HebrewWord: "מעונן חלקית" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es ist schwül", HebrewWord: "לח מאוד" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es ist angenehm", HebrewWord: "נעים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es gibt einen starken Sturm", HebrewWord: "יש סופה חזקה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es gibt leichtes Nieseln", HebrewWord: "יש טפטוף קל" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es regnet in Strömen", HebrewWord: "יורד גשם כבד" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 7, courseName: "Weather", GermanWord: "Es gibt einen Schneesturm", HebrewWord: "יש סופת שלגים" },

// Basic Clothing
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "das Hemd", HebrewWord: "חולצה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Hose", HebrewWord: "מכנסיים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "das Kleid", HebrewWord: "שמלה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Jacke", HebrewWord: "מעיל" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Schuhe", HebrewWord: "נעליים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Socken", HebrewWord: "גרביים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Mütze", HebrewWord: "כובע צמר" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "der Hut", HebrewWord: "כובע" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Handschuhe", HebrewWord: "כפפות" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "der Schal", HebrewWord: "צעיף" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Bluse", HebrewWord: "חולצת נשים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Unterwäsche", HebrewWord: "תחתונים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "das T-Shirt", HebrewWord: "טי-שירט" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Jeans", HebrewWord: "ג'ינס" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Sandalen", HebrewWord: "סנדלים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Stiefel", HebrewWord: "מגפיים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Weste", HebrewWord: "אפוד" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "der Pullover", HebrewWord: "סוודר" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Krawatte", HebrewWord: "עניבה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "das Kostüm", HebrewWord: "חליפה (נשים)" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "der Anzug", HebrewWord: "חליפה (גברים)" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Shorts", HebrewWord: "מכנסיים קצרים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "der Mantel", HebrewWord: "מעיל ארוך" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Strümpfe", HebrewWord: "גרביים ארוכים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "der Gürtel", HebrewWord: "חגורה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Regenjacke", HebrewWord: "מעיל גשם" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "das Nachthemd", HebrewWord: "כתונת לילה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Bademode", HebrewWord: "בגד ים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Hausschuhe", HebrewWord: "נעלי בית" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 8, courseName: "Basic Clothing", GermanWord: "die Schürze", HebrewWord: "סינר" },
// Common Food Items
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "das Brot", HebrewWord: "לחם" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "die Butter", HebrewWord: "חמאה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "die Milch", HebrewWord: "חלב" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "das Ei", HebrewWord: "ביצה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "der Käse", HebrewWord: "גבינה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "der Apfel", HebrewWord: "תפוח" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "die Banane", HebrewWord: "בננה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "die Orange", HebrewWord: "תפוז" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "die Kartoffel", HebrewWord: "תפוח אדמה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "die Tomate", HebrewWord: "עגבנייה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "die Gurke", HebrewWord: "מלפפון" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "der Salat", HebrewWord: "סלט" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "das Fleisch", HebrewWord: "בשר" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "der Fisch", HebrewWord: "דג" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "das Hähnchen", HebrewWord: "עוף" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "der Reis", HebrewWord: "אורז" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "die Nudeln", HebrewWord: "אטריות" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "das Salz", HebrewWord: "מלח" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "der Zucker", HebrewWord: "סוכר" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "der Honig", HebrewWord: "דבש" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "die Marmelade", HebrewWord: "ריבה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "die Schokolade", HebrewWord: "שוקולד" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "das Wasser", HebrewWord: "מים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "der Saft", HebrewWord: "מיץ" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "das Bier", HebrewWord: "בירה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "der Wein", HebrewWord: "יין" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "der Kaffee", HebrewWord: "קפה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "der Tee", HebrewWord: "תה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "die Zwiebel", HebrewWord: "בצל" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 9, courseName: "Common Food Items", GermanWord: "der Knoblauch", HebrewWord: "שום" },

// House Parts
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "das Wohnzimmer", HebrewWord: "סלון" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "das Schlafzimmer", HebrewWord: "חדר שינה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "die Küche", HebrewWord: "מטבח" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "das Badezimmer", HebrewWord: "חדר אמבטיה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "das Esszimmer", HebrewWord: "חדר אוכל" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "das Kinderzimmer", HebrewWord: "חדר ילדים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "der Keller", HebrewWord: "מרתף" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "der Dachboden", HebrewWord: "עליית גג" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "der Flur", HebrewWord: "מסדרון" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "die Tür", HebrewWord: "דלת" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "das Fenster", HebrewWord: "חלון" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "der Garten", HebrewWord: "גן" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "der Balkon", HebrewWord: "מרפסת" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "die Treppe", HebrewWord: "מדרגות" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "das Dach", HebrewWord: "גג" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "die Wand", HebrewWord: "קיר" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "der Boden", HebrewWord: "רצפה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "die Decke", HebrewWord: "תקרה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "die Garage", HebrewWord: "מוסך" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "der Hof", HebrewWord: "חצר" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "die Haustür", HebrewWord: "דלת כניסה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "der Kamin", HebrewWord: "אח" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "die Veranda", HebrewWord: "מרפסת מקורה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "die Waschküche", HebrewWord: "חדר כביסה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "das Büro", HebrewWord: "משרד" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "die Terrasse", HebrewWord: "טרסה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "das Gästezimmer", HebrewWord: "חדר אורחים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "die Vorratskammer", HebrewWord: "מזווה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "das Badezimmer", HebrewWord: "חדר שירותים" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 10, courseName: "House Parts", GermanWord: "die Eingangshalle", HebrewWord: "אולם כניסה" },

// Animals
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "der Hund", HebrewWord: "כלב" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "die Katze", HebrewWord: "חתול" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "das Pferd", HebrewWord: "סוס" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "die Kuh", HebrewWord: "פרה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "das Schwein", HebrewWord: "חזיר" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "das Schaf", HebrewWord: "כבשה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "die Ziege", HebrewWord: "עז" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "der Hase", HebrewWord: "ארנב" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "der Fuchs", HebrewWord: "שועל" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "der Bär", HebrewWord: "דוב" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "der Löwe", HebrewWord: "אריה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "der Tiger", HebrewWord: "טיגריס" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "der Elefant", HebrewWord: "פיל" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "die Maus", HebrewWord: "עכבר" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "der Vogel", HebrewWord: "ציפור" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "der Fisch", HebrewWord: "דג" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "die Schlange", HebrewWord: "נחש" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "die Spinne", HebrewWord: "עכביש" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "der Affe", HebrewWord: "קוף" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "das Känguru", HebrewWord: "קנגורו" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "der Delfin", HebrewWord: "דולפין" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "der Wal", HebrewWord: "לוויתן" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "der Pinguin", HebrewWord: "פינגווין" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "das Krokodil", HebrewWord: "תנין" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "der Schmetterling", HebrewWord: "פרפר" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "die Ameise", HebrewWord: "נמלה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "die Biene", HebrewWord: "דבורה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "der Hahn", HebrewWord: "תרנגול" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "die Ente", HebrewWord: "ברווז" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 11, courseName: "Animals", GermanWord: "die Gans", HebrewWord: "אווז" },

// Basic Emotions
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "glücklich", HebrewWord: "שמח" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "traurig", HebrewWord: "עצוב" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "wütend", HebrewWord: "כועס" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "aufgeregt", HebrewWord: "נרגש" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "ängstlich", HebrewWord: "מפוחד" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "zufrieden", HebrewWord: "מרוצה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "überrascht", HebrewWord: "מופתע" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "gelangweilt", HebrewWord: "משועמם" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "besorgt", HebrewWord: "מודאג" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "verliebt", HebrewWord: "מאוהב" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "neidisch", HebrewWord: "מקנא" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "dankbar", HebrewWord: "מודה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "müde", HebrewWord: "עייף" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "verärgert", HebrewWord: "כועס" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "schüchtern", HebrewWord: "ביישן" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "stolz", HebrewWord: "גאה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "verwirrt", HebrewWord: "מבולבל" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "einsam", HebrewWord: "בודד" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "frustriert", HebrewWord: "מתוסכל" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "hoffnungsvoll", HebrewWord: "מקווה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "erschöpft", HebrewWord: "מותש" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "verletzt", HebrewWord: "נפגע" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "eifersüchtig", HebrewWord: "קנאי" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "beschämt", HebrewWord: "מתבייש" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "entspannt", HebrewWord: "רגוע" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "unwohl", HebrewWord: "לא בנוח" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "aufmerksam", HebrewWord: "קשוב" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "vergnügt", HebrewWord: "מרוצה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "hoffnungslos", HebrewWord: "חסר תקווה" },
{ level_hebrew: "מבוא", level_english: "A1", courseId: 12, courseName: "Basic Emotions", GermanWord: "erleichtert", HebrewWord: "מוקל" },

      
    ]).returning({ id: Words.id });

    console.log("Seeding complete. Inserted items:", items);
  } catch (error) {
    console.error("Error during seeding:", error);
    process.exit(1); // Exit with failure
  }
}

seed();